#include "nouns.h"

#define COUNT_SECTIONS  1

Nouns::Nouns() : BaseAction()
{




    QList<WordPair> List1;
    List1.append(WordPair("angle", "угол, поворачивать"));
    List1.append(WordPair("ant", "муравей"));
    List1.append(WordPair("apple", "яблоко"));
    List1.append(WordPair("arch", "арка, дуга, выгибать"));
    List1.append(WordPair("arm", "рука, вооружать"));
    List1.append(WordPair("army", "армия"));
    List1.append(WordPair("bag", "сумка)"));
    List1.append(WordPair("ball", "мяч"));
    List1.append(WordPair("bank", "банк"));
    List1.append(WordPair("basin", "бассейн"));
    List1.append(WordPair("basket", "корзина"));
    List1.append(WordPair("bath", "ванна, купаться"));
    List1.append(WordPair("bed", "кровать"));
    List1.append(WordPair("bee", "пчела"));
    List1.append(WordPair("bell", "колокольчик"));
    List1.append(WordPair("berry", "ягода	"));
    List1.append(WordPair("bird", "птица"));
    List1.append(WordPair("blade", "лезвие"));
    List1.append(WordPair("board", "доска"));
    List1.append(WordPair("boat", "лодка, судно"));
    List1.append(WordPair("bone", "кость"));
    List1.append(WordPair("book", "книга"));
    List1.append(WordPair("boot", "ботинок, загружать"));
    List1.append(WordPair("bottle", "бутылка"));
    List1.append(WordPair("box", "коробка"));
    List1.append(WordPair("boy", "мальчик	"));
    List1.append(WordPair("brain", "мозг"));
    List1.append(WordPair("brake", "тормоз, тормозить"));
    List1.append(WordPair("branch", "ветвь, отделение"));
    List1.append(WordPair("brick", "кирпич"));
    List1.append(WordPair("bridge", "мост"));
    List1.append(WordPair("brush", "щётка, кисть"));
    List1.append(WordPair("bucket", "ведро, черпать"));
    List1.append(WordPair("bulb", "луковица, выпирать"));
    List1.append(WordPair("button", "кнопка, застёгивать"));
    List1.append(WordPair("baby", "ребёнок, младенец"));
    List1.append(WordPair("cake", "пирог"));
    List1.append(WordPair("camera", "камера"));
    List1.append(WordPair("card", "карта, чесать"));
    List1.append(WordPair("cart", "везти"));
    List1.append(WordPair("carriage", "вагон"));
    List1.append(WordPair("cat", "кот"));
    List1.append(WordPair("chain", "цепь, сеть"));
    List1.append(WordPair("cheese", "сыр	"));
    List1.append(WordPair("chest", "грудь, сундук"));
    List1.append(WordPair("chin", "подбородок"));
    List1.append(WordPair("church", "церковь"));
    List1.append(WordPair("circle", "круг"));
    List1.append(WordPair("clock", "часы"));
    List1.append(WordPair("cloud", "облако"));
    List1.append(WordPair("coat", "пальто, покрывать"));
    List1.append(WordPair("collar", "воротник, хватать	"));
    List1.append(WordPair("comb", "расчёсывать"));
    List1.append(WordPair("cord", "шнур, связывать"));
    List1.append(WordPair("cow", "корова"));
    List1.append(WordPair("cup", "чашка"));
    List1.append(WordPair("curtain", "занавес, штора, занавешивать"));
    List1.append(WordPair("cushion", "подушка, смягчать"));
    List1.append(WordPair("dog", "собака"));
    List1.append(WordPair("door", "дверь	"));
    List1.append(WordPair("drain", "утечка, истощать"));
    List1.append(WordPair("drawer", "ящик	"));
    List1.append(WordPair("dress", "платье, одевать"));
    List1.append(WordPair("drop", "капля, опускать"));
    List1.append(WordPair("ear", "ухо"));
    List1.append(WordPair("egg", "яйцо	"));
    List1.append(WordPair("engine", "двигатель"));
    List1.append(WordPair("eye", "глаз"));
    List1.append(WordPair("face", "лицо"));
    List1.append(WordPair("farm", "ферма"));
    List1.append(WordPair("feather", "перо, украшать"));
    List1.append(WordPair("finger", "палец	"));
    List1.append(WordPair("fish", "рыба"));
    List1.append(WordPair("flag", "флаг, сигнализировать"));
    List1.append(WordPair("floor", "пол, этаж, дно"));
    List1.append(WordPair("fly", "муха, лететь	"));
    List1.append(WordPair("foot", "нога"));
    List1.append(WordPair("fork", "вилка"));
    List1.append(WordPair("fowl", "домашняя птица"));
    List1.append(WordPair("frame", "структура, рамка, создавать"));
    List1.append(WordPair("garden", "сад"));
    List1.append(WordPair("girl", "девочка"));
    List1.append(WordPair("glove", "перчатка	"));
    List1.append(WordPair("goat", "коза"));
    List1.append(WordPair("gun", "оружие"));
    List1.append(WordPair("hair", "волосы"));
    List1.append(WordPair("hammer", "молоток"));
    List1.append(WordPair("hand", "рука"));
    List1.append(WordPair("hat", "шляпа	"));
    List1.append(WordPair("head", "голова"));
    List1.append(WordPair("heart", "сердце"));
    List1.append(WordPair("hook", "крюк, вербовать"));
    List1.append(WordPair("horn", "рожок	"));
    List1.append(WordPair("horse", "лошадь"));
    List1.append(WordPair("hospital", "больница"));
    List1.append(WordPair("house", "дом"));

    List1.append(WordPair("island", "остров"));
    List1.append(WordPair("jewel", "драгоценный камень"));
    List1.append(WordPair("kettle", "чайник"));
    List1.append(WordPair("key", "ключ	"));
    List1.append(WordPair("knee", "колено"));
    List1.append(WordPair("knife", "нож	"));
    List1.append(WordPair("knot", "узел"));
    List1.append(WordPair("leaf", "лист, покрывать листвой"));
    List1.append(WordPair("leg", "нога	"));
    List1.append(WordPair("library", "библиотека"));
    List1.append(WordPair("line", "линия, очередь, выравнивать	"));
    List1.append(WordPair("lip", "губа"));
    List1.append(WordPair("lock", "замок"));
    List1.append(WordPair("map", "карта"));
    List1.append(WordPair("match", "спичка, сделки, соответствовать	"));
    List1.append(WordPair("monkey", "обезьяна"));
    List1.append(WordPair("moon", "луна	"));
    List1.append(WordPair("mouth", "рот, жевать"));
    List1.append(WordPair("muscle", "мускул"));
    List1.append(WordPair("nail", "ноготь"));
    List1.append(WordPair("neck", "шея, обниматься"));
    List1.append(WordPair("needle", "игла	"));
    List1.append(WordPair("nerve", "нерв"));
    List1.append(WordPair("net", "чистый, сеть	"));
    List1.append(WordPair("nose", "нос"));
    List1.append(WordPair("nut", "орех"));
    List1.append(WordPair("office", "офис	"));
    List1.append(WordPair("orange", "апельсин, оранжевый	"));
    List1.append(WordPair("oven", "духовка, печь"));
    List1.append(WordPair("parcel", "пакет, распределять"));
    List1.append(WordPair("pen", "ручка"));
    List1.append(WordPair("pencil", "карандаш"));
    List1.append(WordPair("picture", "картина"));
    List1.append(WordPair("pig", "свинья	"));
    List1.append(WordPair("pin", "булавка, прикреплять"));
    List1.append(WordPair("pipe", "труба"));
    List1.append(WordPair("plane", "самолёт"));
    List1.append(WordPair("plate", "пластина"));
    List1.append(WordPair("plow", "плуг, пахать	"));
    List1.append(WordPair("pocket", "карман, присваивать"));
    List1.append(WordPair("pot", "горшок"));
    List1.append(WordPair("potato", "картофель"));
    List1.append(WordPair("prison", "тюрьма"));
    List1.append(WordPair("pump", "насос, качать"));
    List1.append(WordPair("rail", "рельс, перевозить поездом"));
    List1.append(WordPair("rat", "крыса"));
    List1.append(WordPair("receipt", "квитанция	"));
    List1.append(WordPair("ring", "кольцо, звонить"));
    List1.append(WordPair("rod", "прут	"));
    List1.append(WordPair("roof", "крыша"));
    List1.append(WordPair("root", "корень"));
    List1.append(WordPair("sail", "парус"));
    List1.append(WordPair("school", "школа"));
    List1.append(WordPair("scissors", "ножницы"));
    List1.append(WordPair("screw", "винт"));
    List1.append(WordPair("seed", "семя"));
    List1.append(WordPair("sheep", "овцы"));
    List1.append(WordPair("shelf", "полка"));
    List1.append(WordPair("ship", "корабль"));
    List1.append(WordPair("shirt", "рубашка"));
    List1.append(WordPair("shoe", "ботинок	"));
    List1.append(WordPair("skin", "кожа, очищать"));
    List1.append(WordPair("skirt", "юбка"));
    List1.append(WordPair("snake", "змея"));
    List1.append(WordPair("sock", "носок"));
    List1.append(WordPair("spade", "лопата"));
    List1.append(WordPair("sponge", "губка"));
    List1.append(WordPair("spoon", "ложка"));
    List1.append(WordPair("spring", "весна"));
    List1.append(WordPair("square", "квадрат"));
    List1.append(WordPair("stamp", "печать, марка, отпечатывать	"));
    List1.append(WordPair("star", "звезда"));
    List1.append(WordPair("station", "станция"));
    List1.append(WordPair("stem", "стебель, происходить"));
    List1.append(WordPair("stick", "палка, прикреплять"));
    List1.append(WordPair("stocking", "снабжать"));
    List1.append(WordPair("stomach", "живот, смелость, переваривать"));
    List1.append(WordPair("store", "магазин, запас"));
    List1.append(WordPair("street", "улица"));
    List1.append(WordPair("sun", "солнце"));
    List1.append(WordPair("table", "стол"));
    List1.append(WordPair("tail", "хвост, выслеживать"));
    List1.append(WordPair("thread", "нить, пронизывать"));
    List1.append(WordPair("throat", "горло"));
    List1.append(WordPair("thumb", "листать, большой палец	"));
    List1.append(WordPair("ticket", "билет"));
    List1.append(WordPair("toe", "палец ноги"));
    List1.append(WordPair("tongue", "язык"));
    List1.append(WordPair("tooth", "зуб"));
    List1.append(WordPair("town", "город	"));
    List1.append(WordPair("train", "поезд"));
    List1.append(WordPair("tray", "поднос"));
    List1.append(WordPair("tree", "дерево"));
    List1.append(WordPair("trousers", "брюки"));
    List1.append(WordPair("umbrella", "зонт"));
    List1.append(WordPair("wall", "стена"));
    List1.append(WordPair("watch", "часы"));
    List1.append(WordPair("wheel", "колесо, вертеть	"));
    List1.append(WordPair("whip", "кнут, хлестать"));
    List1.append(WordPair("whistle", "свист, свистеть"));
    List1.append(WordPair("window", "окно	"));
    List1.append(WordPair("wing", "крыло"));
    List1.append(WordPair("wire", "провод"));
    List1.append(WordPair("worm", "червь"));
    List1.append(WordPair("account", "счет, считать"));
    List1.append(WordPair("act", "действия"));
    List1.append(WordPair("addition", "дополнение"));
    List1.append(WordPair("adjust", "регулировать, приспосабливать"));
    List1.append(WordPair("advertisement", "реклама"));
    List1.append(WordPair("agreement", "соглашение"));
    List1.append(WordPair("air", "воздух, проветривать	"));
    List1.append(WordPair("amount", "количество, означать, составлять"));
    List1.append(WordPair("amusement", "развлечение"));
    List1.append(WordPair("animal", "животное"));
    List1.append(WordPair("answer", "ответ, отвечать"));
    List1.append(WordPair("apparatus", "аппарат"));
    List1.append(WordPair("approval", "одобрение"));
    List1.append(WordPair("argument", "спор, аргумент	"));
    List1.append(WordPair("art", "искусство, художественный"));
    List1.append(WordPair("attack", "нападение, нападать"));
    List1.append(WordPair("attempt", "попытка, пытаться"));
    List1.append(WordPair("attention", "внимание"));
    List1.append(WordPair("attraction", "достопримечательности"));
    List1.append(WordPair("authority", "власть, полномочие"));
    List1.append(WordPair("back", "назад, спина, отступать"));
    List1.append(WordPair("balance", "баланс, уравновешивать"));
    List1.append(WordPair("base", "основной"));
    List1.append(WordPair("behavior", "поведение"));
    List1.append(WordPair("belief", "вера"));
    List1.append(WordPair("birth", "рождение"));
    List1.append(WordPair("bit", "частица, бит	"));
    List1.append(WordPair("bite", "укус, кусать"));
    List1.append(WordPair("blood", "кровь"));
    List1.append(WordPair("blow", "удар, дуть"));
    List1.append(WordPair("body", "тело"));
    List1.append(WordPair("brass", "медь, руководство"));
    List1.append(WordPair("bread", "хлеб"));
    List1.append(WordPair("breath", "дыхание	"));
    List1.append(WordPair("brother", "брат"));
    List1.append(WordPair("building", "здание, строение"));
    List1.append(WordPair("burn", "ожог, гореть"));
    List1.append(WordPair("burst", "взрыв, взрывать"));
    List1.append(WordPair("business", "бизнес, деловой"));
    List1.append(WordPair("butter", "масло"));
    List1.append(WordPair("canvas", "холст"));
    List1.append(WordPair("care", "забота, лечение"));
    List1.append(WordPair("cause", "причина, вызывать"));
    List1.append(WordPair("chalk", "мел, рисовать мелом"));
    List1.append(WordPair("chance", "шанс, случайный, рисковать"));
    List1.append(WordPair("change", "изменение, замена"));
    List1.append(WordPair("cloth", "ткань, одежда"));
    List1.append(WordPair("coal", "уголь"));
    List1.append(WordPair("color", "цвет"));
    List1.append(WordPair("comfort", "комфорт"));
    List1.append(WordPair("committee", "комитет	"));
    List1.append(WordPair("company", "компания"));
    List1.append(WordPair("comparison", "сравнение"));
    List1.append(WordPair("competition", "соревнование"));
    List1.append(WordPair("condition", "условие, обуславливать"));
    List1.append(WordPair("connection", "связь"));
    List1.append(WordPair("control", "контроль"));
    List1.append(WordPair("cook", "готовить"));
    List1.append(WordPair("copper", "медь"));
    List1.append(WordPair("copy", "копия"));
    List1.append(WordPair("cork", "пробка"));
    List1.append(WordPair("cotton", "хлопок	"));
    List1.append(WordPair("cough", "кашель"));
    List1.append(WordPair("country", "страна"));
    List1.append(WordPair("cover", "покрытие, покрывать, обложка"));
    List1.append(WordPair("crack", "первоклассный, взламывать"));
    List1.append(WordPair("credit", "кредит, верить"));
    List1.append(WordPair("crime", "преступление"));
    List1.append(WordPair("crush", "давка, сокрушать"));
    List1.append(WordPair("cry", "плакать"));
    List1.append(WordPair("current", "текущий, поток"));
    List1.append(WordPair("curve", "кривая, избегать"));
    List1.append(WordPair("damage", "повреждение, повреждать"));
    List1.append(WordPair("danger", "опасность"));
    List1.append(WordPair("daughter", "дочь"));
    List1.append(WordPair("day", "день"));
    List1.append(WordPair("death", "смерть"));
    List1.append(WordPair("debt", "долг"));
    List1.append(WordPair("decision", "решение"));
    List1.append(WordPair("degree", "уровень, градус, степень"));
    List1.append(WordPair("design", "намереваться"));
    List1.append(WordPair("desire", "желание, желать	"));
    List1.append(WordPair("destruction", "разрушение"));
    List1.append(WordPair("detail", "детализировать, детали"));
    List1.append(WordPair("development", "развитие"));
    List1.append(WordPair("digestion", "вываривание"));
    List1.append(WordPair("direction", "управление"));
    List1.append(WordPair("discovery", "открытие"));
    List1.append(WordPair("discussion", "обсуждение"));
    List1.append(WordPair("disease", "болезнь"));
    List1.append(WordPair("disgust", "отвращение	"));
    List1.append(WordPair("distance", "дистанция"));
    List1.append(WordPair("distribution", "распределение"));
    List1.append(WordPair("division", "подразделение"));
    List1.append(WordPair("doubt", "сомнение"));
    List1.append(WordPair("drink", "пить, напиток"));
    List1.append(WordPair("driving", "вождение"));
    List1.append(WordPair("dust", "чистить, пыль"));
    List1.append(WordPair("earth", "земля"));
    List1.append(WordPair("edge", "продвигаться, край"));
    List1.append(WordPair("education", "образование"));
    List1.append(WordPair("effect", "производить, эффект"));
    List1.append(WordPair("end", "заканчивать, конец	"));
    List1.append(WordPair("error", "ошибка"));
    List1.append(WordPair("event", "случай, событие"));
    List1.append(WordPair("example", "пример"));
    List1.append(WordPair("exchange", "обмен, обменивать"));
    List1.append(WordPair("existence", "существование	"));
    List1.append(WordPair("expansion", "расширение"));
    List1.append(WordPair("experience", "опыт, испытывать"));
    List1.append(WordPair("expert", "опытный, эксперт"));
    List1.append(WordPair("fact", "факт"));
    List1.append(WordPair("fall", "падение, осень"));
    List1.append(WordPair("family", "семья"));
    List1.append(WordPair("father", "папа"));
    List1.append(WordPair("fear", "бояться, страх"));
    List1.append(WordPair("feeling", "чувство"));
    List1.append(WordPair("fiction", "беллетристика, фикция	"));
    List1.append(WordPair("field", "область, поле, выставлять"));
    List1.append(WordPair("fight", "борьба, бороться"));
    List1.append(WordPair("fire", "огонь"));
    List1.append(WordPair("flame", "пылать, пламя"));
    List1.append(WordPair("flight", "полет, рейс"));
    List1.append(WordPair("flower", "цветок"));
    List1.append(WordPair("fold", "сгиб, сворачивать	"));
    List1.append(WordPair("food", "еда, продовольствие"));
    List1.append(WordPair("force", "сила, вынуждать, вызывать"));
    List1.append(WordPair("form", "форма"));
    List1.append(WordPair("friend", "друг"));
    List1.append(WordPair("front", "выходить, фронт, передний"));
    List1.append(WordPair("fruit", "фрукт"));
    List1.append(WordPair("glass", "стекло, стакан"));
    List1.append(WordPair("gold", "золото"));
    List1.append(WordPair("government", "государство	"));
    List1.append(WordPair("grain", "зерно"));
    List1.append(WordPair("grass", "трава"));
    List1.append(WordPair("grip", "власть, захват, захватывать	"));
    List1.append(WordPair("group", "группа"));
    List1.append(WordPair("growth", "рост"));
    List1.append(WordPair("guide", "гид, справочник, путеводитель"));
    List1.append(WordPair("harbor", "приютить, питать, вставать на якорь, гавань"));
    List1.append(WordPair("harmony", "гармония"));
    List1.append(WordPair("hate", "ненавидеть, очень не хотеть, ненависть"));
    List1.append(WordPair("hearing", "слушание, слух	"));
    List1.append(WordPair("heat", "нагревать, высокая температура"));
    List1.append(WordPair("help", "помощь, помогать"));
    List1.append(WordPair("history", "история"));
    List1.append(WordPair("hole", "продырявливать, отверстие"));
    List1.append(WordPair("hope", "надежда, надеяться"));
    List1.append(WordPair("hour", "час"));
    List1.append(WordPair("humor", "юмор"));
    List1.append(WordPair("ice", "лёд"));
    List1.append(WordPair("idea", "идея"));
    List1.append(WordPair("impulse", "импульс"));
    List1.append(WordPair("increase", "увеличивать, увеличение	"));
    List1.append(WordPair("industry", "индустрия"));
    List1.append(WordPair("ink", "чернила"));
    List1.append(WordPair("insect", "насекомое"));
    List1.append(WordPair("instrument", "инструмент	"));
    List1.append(WordPair("insurance", "страховка"));
    List1.append(WordPair("interest", "интерес, процент, доля"));
    List1.append(WordPair("invention", "изобретение"));
    List1.append(WordPair("iron", "утюг, гладить"));
    List1.append(WordPair("jelly", "превращать в желе, желе"));
    List1.append(WordPair("join", "присоединяться, объединение, соединение	"));
    List1.append(WordPair("journey", "путешествовать, поездка"));
    List1.append(WordPair("judge", "судья, судить	"));
    List1.append(WordPair("jump", "прыгать, прыжок"));
//    List1.append(WordPair("K:"));
    List1.append(WordPair("kick", "удар, ударить	"));
    List1.append(WordPair("kiss", "поцелуй, целовать	"));
    List1.append(WordPair("knowledge", "знание"));
//    List1.append(WordPair("L:"));
    List1.append(WordPair("land", "земля"));
    List1.append(WordPair("language", "язык"));
    List1.append(WordPair("laugh", "смеяться, смех"));
    List1.append(WordPair("law", "законный, закон"));
    List1.append(WordPair("lead", "принуждать, побеждать, вести, лидерство"));
    List1.append(WordPair("learning", "изучение, обучение	"));
    List1.append(WordPair("leather", "кожа"));
    List1.append(WordPair("letter", "письмо"));
    List1.append(WordPair("level", "уровень, выравнивать, направлять"));
    List1.append(WordPair("lift", "поднимать, лифт"));
    List1.append(WordPair("light", "освещать, легкий, свет"));
    List1.append(WordPair("limit", "ограничивать	"));
    List1.append(WordPair("linen", "льняной, полотно"));
    List1.append(WordPair("liquid", "жидкий, жидкость"));
    List1.append(WordPair("list", "список, перечислять"));
    List1.append(WordPair("loss", "потеря"));
    List1.append(WordPair("love", "любовь"));
//    List1.append(WordPair("M:"));
    List1.append(WordPair("machine", "машина"));
    List1.append(WordPair("man", "человек"));
    List1.append(WordPair("mark", "марка"));
    List1.append(WordPair("market", "рынок"));
    List1.append(WordPair("mass", "масса"));
    List1.append(WordPair("meal", "еда"));
    List1.append(WordPair("measure", "мера, измерять"));
    List1.append(WordPair("meat", "мясо"));
    List1.append(WordPair("meeting", "встреча	"));
    List1.append(WordPair("memory", "память"));
    List1.append(WordPair("metal", "металл"));
    List1.append(WordPair("middle", "средний, середина"));
    List1.append(WordPair("milk", "молоко"));
    List1.append(WordPair("mind", "ум, возражать"));
    List1.append(WordPair("mine", "мой, месторождение, мина"));
    List1.append(WordPair("minute", "минута"));
    List1.append(WordPair("mist", "туман"));
    List1.append(WordPair("money", "деньги	"));
    List1.append(WordPair("month", "месяц"));
    List1.append(WordPair("morning", "утро"));
    List1.append(WordPair("mother", "мать"));
    List1.append(WordPair("motion", "двигаться, движение, жест"));
    List1.append(WordPair("mountain", "гора, горный"));
    List1.append(WordPair("move", "двигать, шаг, движение"));
    List1.append(WordPair("music", "музыка"));
//    List1.append(WordPair("N:"));
    List1.append(WordPair("name", "имя"));
    List1.append(WordPair("nation", "нация"));
    List1.append(WordPair("need", "потребность, требоваться	"));
    List1.append(WordPair("news", "новости"));
    List1.append(WordPair("night", "ночь"));
    List1.append(WordPair("noise", "шум	"));
    List1.append(WordPair("note", "примечание, отмечать"));
    List1.append(WordPair("number", "число, номер"));
//    List1.append(WordPair("O:"));
    List1.append(WordPair("observation", "наблюдение"));
    List1.append(WordPair("offer", "предложение, предлагать"));
    List1.append(WordPair("oil", "масло	"));
    List1.append(WordPair("operation", "операция, действие"));
    List1.append(WordPair("opinion", "мнение"));
    List1.append(WordPair("order", "заказ, заказывать, приказывать	"));
    List1.append(WordPair("organization", "организация"));
    List1.append(WordPair("ornament", "украшение, украшать"));
    List1.append(WordPair("owner", "владелец"));
//    List1.append(WordPair("P:"));
    List1.append(WordPair("page", "страница"));
    List1.append(WordPair("pain", "боль, причинять боль"));
    List1.append(WordPair("paint", "краска, рисовать, красить"));
    List1.append(WordPair("paper", "бумага"));
    List1.append(WordPair("part", "часть, отделять, разделяться"));
    List1.append(WordPair("paste", "приклеивать, паста"));
    List1.append(WordPair("payment", "оплата"));
    List1.append(WordPair("peace", "мир"));
    List1.append(WordPair("person", "персона"));
    List1.append(WordPair("place", "размещать, помещать, занимать место, место"));
    List1.append(WordPair("plant", "завод, растение, прививать, сеять	"));
    List1.append(WordPair("play", "играть"));
    List1.append(WordPair("pleasure", "удовольствие"));
    List1.append(WordPair("point", "пункт, точка, указывать"));
    List1.append(WordPair("poison", "яд, отравлять"));
    List1.append(WordPair("polish", "полировать"));
    List1.append(WordPair("porter", "швейцар,носильщик"));
    List1.append(WordPair("position", "помещать, позиция"));
    List1.append(WordPair("powder", "порошок"));
    List1.append(WordPair("power", "сила, власть"));
    List1.append(WordPair("price", "цена"));
    List1.append(WordPair("print", "печатать 	"));
    List1.append(WordPair("process", "обрабатывать, процесс"));
    List1.append(WordPair("produce", "продукт, производить"));
    List1.append(WordPair("profit", "прибыль, получать прибыль"));
    List1.append(WordPair("property", "свойства"));
    List1.append(WordPair("prose", "проза"));
    List1.append(WordPair("protest", "возражать, протест"));
    List1.append(WordPair("pull", "напряжение, тянуть"));
    List1.append(WordPair("punishment", "наказание"));
    List1.append(WordPair("purpose", "намереваться, цель"));
    List1.append(WordPair("push", "толчок, подталкивать"));
//    List1.append(WordPair("Q:"));
    List1.append(WordPair("quality", "качество, качественный	"));
    List1.append(WordPair("question", "вопрос	 "));
//    List1.append(WordPair("R:"));
    List1.append(WordPair("rain", "дождь"));
    List1.append(WordPair("range", "диапазон, располагаться"));
    List1.append(WordPair("rate", "норма,разряд"));
    List1.append(WordPair("ray", "луч"));
    List1.append(WordPair("reaction", "реакция"));
    List1.append(WordPair("reading", "чтение"));
    List1.append(WordPair("reason", "рассуждать, причина, разум"));
    List1.append(WordPair("record", "рекордный, отчёт, делать запись"));
    List1.append(WordPair("regret", "сожаление, сожалеть	"));
    List1.append(WordPair("relation", "отношение"));
    List1.append(WordPair("religion", "религия"));
    List1.append(WordPair("representative", "представитель"));
    List1.append(WordPair("request", "запрос, просить"));
    List1.append(WordPair("respect", "уважение, уважать"));
    List1.append(WordPair("rest", "отдых, отдыхать, оставаться"));
    List1.append(WordPair("reward", "награда, вознаграждать"));
    List1.append(WordPair("rhythm", "ритм"));
    List1.append(WordPair("rice", "рис	"));
    List1.append(WordPair("river", "река"));
    List1.append(WordPair("road", "дорога"));
    List1.append(WordPair("roll", "рулон, ведомость, катиться, въезжать"));
    List1.append(WordPair("room", "комната"));
    List1.append(WordPair("rub", "протирать, тереться"));
    List1.append(WordPair("rule", "правило"));
    List1.append(WordPair("run", "бег, бегать"));
//    List1.append(WordPair("S:"));
    List1.append(WordPair("salt", "соль, солить"));
    List1.append(WordPair("sand", "песок"));
    List1.append(WordPair("scale", "измерять, масштаб"));
    List1.append(WordPair("science", "наука"));
    List1.append(WordPair("sea", "море"));
    List1.append(WordPair("seat", "сиденье, усаживать, место"));
    List1.append(WordPair("secretary", "секретарь"));
    List1.append(WordPair("selection", "выбор"));
    List1.append(WordPair("self", "сам"));
    List1.append(WordPair("sense", "чувство, значения, смысл, ощущать"));
    List1.append(WordPair("servant", "слуга"));
    List1.append(WordPair("sex", "секс, пол"));
    List1.append(WordPair("shade", "оттенок,тень, заштриховывать"));
    List1.append(WordPair("shake", "встряска, встряхивать, дрожать, потрясать"));
    List1.append(WordPair("shame", "позор, позорить"));
    List1.append(WordPair("shock", "шок, потрясать"));
    List1.append(WordPair("side", "сторона, примыкать"));
    List1.append(WordPair("sign", "знак, признак, подписывать"));
    List1.append(WordPair("silk", "шёлк"));
    List1.append(WordPair("silver", "серебро	"));
    List1.append(WordPair("sister", "сестра"));
    List1.append(WordPair("size", "размер"));
    List1.append(WordPair("sky", "небо"));
    List1.append(WordPair("sleep", "спать"));
    List1.append(WordPair("slip", "промах, бланк, подсовывать, скользить"));
    List1.append(WordPair("slope", "наклон, клониться"));
    List1.append(WordPair("smash", "удар, разбиваться"));
    List1.append(WordPair("smell", "запах, пахнуть"));
    List1.append(WordPair("smile", "улыбка, улыбаться"));
    List1.append(WordPair("smoke", "дым, курить"));
    List1.append(WordPair("sneeze", "чиханье, чихать"));
    List1.append(WordPair("snow", "снег"));
    List1.append(WordPair("soap", "мыло, мылить"));
    List1.append(WordPair("society", "общество"));
    List1.append(WordPair("son", "сын"));
    List1.append(WordPair("song", "песня"));
    List1.append(WordPair("sort", "вид, сортировать"));
    List1.append(WordPair("sound", "звук"));
    List1.append(WordPair("soup", "суп"));
    List1.append(WordPair("space", "пространство, космос	"));
    List1.append(WordPair("stage", "стадия, сцена, организовывать"));
    List1.append(WordPair("start", "начинать"));
    List1.append(WordPair("statement", "утверждение"));
    List1.append(WordPair("steam", "пар, париться, двигаться"));
    List1.append(WordPair("steel", "сталь"));
    List1.append(WordPair("step", "шаг, шагать"));
    List1.append(WordPair("stitch", "стежок, сшивать"));
    List1.append(WordPair("stone", "камень"));
    List1.append(WordPair("stop", "останавливаться, остановка"));
    List1.append(WordPair("story", "история"));
    List1.append(WordPair("stretch", "отрезки, протягивать, простираться"));
    List1.append(WordPair("structure", "структура"));
    List1.append(WordPair("substance", "вещество, сущность"));
    List1.append(WordPair("sugar", "сахар"));
    List1.append(WordPair("suggestion", "предложение, предположение"));
    List1.append(WordPair("summer", "лето"));
    List1.append(WordPair("support", "поддержка, поддерживать"));
    List1.append(WordPair("surprise", "сюрприз"));
    List1.append(WordPair("swim", "плаванье, плавать"));
    List1.append(WordPair("system", "система"));
//    List1.append(WordPair("T:"));
    List1.append(WordPair("talk", "разговор, говорить"));
    List1.append(WordPair("taste", "вкус, испытывать"));
    List1.append(WordPair("tax", "налог, облагать налогом"));
    List1.append(WordPair("teaching", "обучение"));
    List1.append(WordPair("tendency", "тенденция"));
    List1.append(WordPair("test", "проверять, тест"));
    List1.append(WordPair("theory", "теория	"));
    List1.append(WordPair("thing", "вещь"));
    List1.append(WordPair("thought", "мысль"));
    List1.append(WordPair("thunder", "гром, греметь"));
    List1.append(WordPair("time", "время"));
    List1.append(WordPair("tin", "олово,консервная банка"));
    List1.append(WordPair("top", "возглавлять, вершина, главный"));
    List1.append(WordPair("touch", "прикосновение, касаться	"));
    List1.append(WordPair("trade", "торговля, обменивать"));
    List1.append(WordPair("transport ", "транспорт, транспортировать"));
    List1.append(WordPair("trick", "уловка, обманывать"));
    List1.append(WordPair("trouble", "проблема, беспокоить"));
    List1.append(WordPair("turn", "поворот, поворачивать"));
    List1.append(WordPair("twist", "завихрение, крутить"));
//    List1.append(WordPair("U:"));
    List1.append(WordPair("unit", "единица	"));
    List1.append(WordPair("use", "использование, использовать	 "));
//    List1.append(WordPair("V:"));
    List1.append(WordPair("value", "ценность, оценивать"));
    List1.append(WordPair("verse", "стих	"));
    List1.append(WordPair("vessel", "судно, сосуд"));
    List1.append(WordPair("view", "вид, взгляд, рассматривать	"));
    List1.append(WordPair("voice", "голос, высказывать"));
//    List1.append(WordPair("W:"));
    List1.append(WordPair("war", "война"));
    List1.append(WordPair("wash", "мытьё, стирать, чистить"));
    List1.append(WordPair("waste", "ненужный, отходы, трата"));
    List1.append(WordPair("water", "вода"));
    List1.append(WordPair("wave", "волна"));
    List1.append(WordPair("wax", "воск, натирать воском"));
    List1.append(WordPair("weather", "погода	"));
    List1.append(WordPair("week", "неделя"));
    List1.append(WordPair("weight", "вес, нагружать"));
    List1.append(WordPair("wind", "ветер"));
    List1.append(WordPair("wine", "вино"));
    List1.append(WordPair("winter", "зима, зимовать"));
    List1.append(WordPair("woman", "женщина"));
    List1.append(WordPair("wood", "лес	"));
    List1.append(WordPair("wool", "шерсть"));
    List1.append(WordPair("word", "слово"));
    List1.append(WordPair("work", "работа, работать"));
    List1.append(WordPair("wound", "проветривать, рана, ранить"));
    List1.append(WordPair("writing", "письмо"));
//    List1.append(WordPair("Y:"));
    List1.append(WordPair("year", "год"));
    List1.append(WordPair("come", "приходить, приезжать"));
    List1.append(WordPair("get", "получать, заставлять"));
    List1.append(WordPair("give", "давать"));
    List1.append(WordPair("go", "ходить, идти"));
    List1.append(WordPair("keep", "продолжать, держать, оставлять, не допускать"));
    List1.append(WordPair("let", "позволять"));
    List1.append(WordPair("make", "делать/сделать, заставлять"));
    List1.append(WordPair("put", "помещать"));
    List1.append(WordPair("seem", "казаться, представляться"));
    List1.append(WordPair("take", "брать/взять"));
    List1.append(WordPair("be", "быть"));
    List1.append(WordPair("do", "делать"));
    List1.append(WordPair("have", "иметь, съесть, знать"));
    List1.append(WordPair("say", "говорить"));
    List1.append(WordPair("see", "видеть"));
    List1.append(WordPair("send", "посылать"));
    List1.append(WordPair("may", "мочь"));
    List1.append(WordPair("will", "быть хотеть"));
    List1.append(WordPair("about", "о"));
    List1.append(WordPair("across", "через"));
    List1.append(WordPair("after", "после"));
    List1.append(WordPair("against", "против"));
    List1.append(WordPair("among", "среди"));
    List1.append(WordPair("at", "в"));
    List1.append(WordPair("before", "перед"));
    List1.append(WordPair("between", "между"));
    List1.append(WordPair("by", "к, в соответствии с, за, на"));
    List1.append(WordPair("down", "вниз"));
    List1.append(WordPair("from", "из"));
    List1.append(WordPair("in", "в"));
    List1.append(WordPair("off", "прочь, от"));
    List1.append(WordPair("on", "на"));
    List1.append(WordPair("over", "по"));
    List1.append(WordPair("through", "через	"));
    List1.append(WordPair("to", "к, до, в"));
    List1.append(WordPair("under", "под"));
    List1.append(WordPair("up", "вверх"));
    List1.append(WordPair("with", "с"));
    List1.append(WordPair("as", "поскольку, как"));
    List1.append(WordPair("for", "для"));
    List1.append(WordPair("of", "из, о, от"));
    List1.append(WordPair("till", "пока, до"));
    List1.append(WordPair("than", "чем"));
    List1.append(WordPair("a", "любой, один, каждый, некий"));
    List1.append(WordPair("all", "все, весь"));
    List1.append(WordPair("any", "любой, никто"));
    List1.append(WordPair("every", "каждый"));
    List1.append(WordPair("no", "никакой, нет"));
    List1.append(WordPair("other", "другой"));
    List1.append(WordPair("some", "некоторый, немного"));
    List1.append(WordPair("such", "такой, таким образом"));
    List1.append(WordPair("that", "что"));
    List1.append(WordPair("this", "это, этот"));
    List1.append(WordPair("i", "я"));
    List1.append(WordPair("he", "он"));
    List1.append(WordPair("you", "ты, вы"));
    List1.append(WordPair("who", "кто"));
    List1.append(WordPair("and", "и"));
    List1.append(WordPair("because", "потому что"));
    List1.append(WordPair("but", "а, но"));
    List1.append(WordPair("or", "или"));
    List1.append(WordPair("if", "если"));
    List1.append(WordPair("though", "хотя"));
    List1.append(WordPair("while", "в то время как"));
    List1.append(WordPair("how", "как"));
    List1.append(WordPair("when", "когда"));
    List1.append(WordPair("where", "где, куда, откуда	"));
    List1.append(WordPair("why", "почему"));
    List1.append(WordPair("again", "снова"));
    List1.append(WordPair("ever", "когда-либо, никогда"));
    List1.append(WordPair("far", "самый дальний"));
    List1.append(WordPair("forward", "отправлять, вперед"));
    List1.append(WordPair("here", "здесь, сюда"));
    List1.append(WordPair("near", "рядом, около"));
    List1.append(WordPair("now", "теперь, сейчас"));
    List1.append(WordPair("out", "вне, снаружи "));
    List1.append(WordPair("still", "все еще"));
    List1.append(WordPair("then", "тогда"));
    List1.append(WordPair("there", "там, туда"));
    List1.append(WordPair("together", "вместе"));
    List1.append(WordPair("well", "хорошо, намного"));
    List1.append(WordPair("almost", "почти"));
    List1.append(WordPair("enough", "достаточно"));
    List1.append(WordPair("even", "еще, даже"));
    List1.append(WordPair("little", "маленький"));
    List1.append(WordPair("much", "много"));
    List1.append(WordPair("not", "не"));
    List1.append(WordPair("only", "только"));
    List1.append(WordPair("quite", "весьма"));
    List1.append(WordPair("so", "так"));
    List1.append(WordPair("very", "очень"));
    List1.append(WordPair("tomorrow", "завтра"));
    List1.append(WordPair("yesterday", "вчера"));
    List1.append(WordPair("north", "север"));
    List1.append(WordPair("south", "юг"));
    List1.append(WordPair("east", "восток"));
    List1.append(WordPair("west", "запад"));
    List1.append(WordPair("please", "пожалуйста"));
    List1.append(WordPair("yes", "да"));
//    List1.append(WordPair("A:"));
    List1.append(WordPair("able", "способный, быть в состоянии	"));
    List1.append(WordPair("acid", "кислота, кислый	"));
    List1.append(WordPair("angry", "сердитый"));
//    List1.append(WordPair("B:"));
    List1.append(WordPair("beautiful", "красивый"));
    List1.append(WordPair("black", "чёрный	"));
    List1.append(WordPair("boiling", "кипение"));
    List1.append(WordPair("bright", "яркий, умный	"));
    List1.append(WordPair("broken", "сломанный"));
    List1.append(WordPair("brown", "коричневый"));
//    List1.append(WordPair("C:"));
    List1.append(WordPair("cheap", "дешёвый"));
    List1.append(WordPair("chemical", "химикат"));
    List1.append(WordPair("chief", "главный	"));
    List1.append(WordPair("clean", "чистый, чистить"));
    List1.append(WordPair("clear", "ясный, очищать, оправдываться"));
    List1.append(WordPair("common", "общий	"));
    List1.append(WordPair("complex", "комплекс"));
    List1.append(WordPair("conscious", "сознательный"));
    List1.append(WordPair("cut", "резать"));
//    List1.append(WordPair("D:"));
    List1.append(WordPair("deep", "глубокий, глубоко	"));
    List1.append(WordPair("dependent", "зависимый	 "));
//    List1.append(WordPair("E:"));
    List1.append(WordPair("early", "рано, ранний	"));
    List1.append(WordPair("elastic", "эластичный	"));
    List1.append(WordPair("equal", "равный, равняться"));
//    List1.append(WordPair("F:"));
    List1.append(WordPair("fat", "толстый, жир"));
    List1.append(WordPair("fertile", "плодородный"));
    List1.append(WordPair("first", "первый	"));
    List1.append(WordPair("fixed", "неподвижный, неизменный"));
    List1.append(WordPair("flat", "плоский, квартира, плоскость"));
    List1.append(WordPair("free", "свобода, бесплатный	"));
    List1.append(WordPair("frequent", "частый, часто посещать"));
    List1.append(WordPair("full", "полный"));
//    List1.append(WordPair("G:"));
    List1.append(WordPair("general", "общий, генерал"));
    List1.append(WordPair("good", "хороший	"));
    List1.append(WordPair("great", "великий, великолепный"));
    List1.append(WordPair("grey|gray", "серый	 "));
//    List1.append(WordPair("H:"));
    List1.append(WordPair("hanging", "вывешивание, висение"));
    List1.append(WordPair("happy", "счастье	"));
    List1.append(WordPair("hard", "трудный, тяжёлый, твёрдый"));
    List1.append(WordPair("healthy", "здоровый	"));
    List1.append(WordPair("high", "высокий, высоко"));
    List1.append(WordPair("hollow", "пустота"));
//    List1.append(WordPair("I:"));
    List1.append(WordPair("important", "важный	 	 "));
//    List1.append(WordPair("J:"));
    List1.append(WordPair("jewel", "драгоценный камень	 	 "));
//    List1.append(WordPair("K:"));
    List1.append(WordPair("kind", "добрый, вид	 	 "));
//    List1.append(WordPair("L:"));
    List1.append(WordPair("like", "подобный, любить, нравиться	"));
    List1.append(WordPair("living", "проживаниe	"));
    List1.append(WordPair("long", "долго, длинный"));
//    List1.append(WordPair("M:"));
    List1.append(WordPair("male", "мужской, мужчина"));
    List1.append(WordPair("married", "женатый, замужем	"));
    List1.append(WordPair("material", "материал"));
    List1.append(WordPair("medical", "медицинский	"));
    List1.append(WordPair("military", "военный"));
//    List1.append(WordPair("N:"));
    List1.append(WordPair("natural", "натуральный"));
    List1.append(WordPair("necessary", "необходимый	"));
    List1.append(WordPair("new", "новый"));
    List1.append(WordPair("normal", "нормальный	 "));
//    List1.append(WordPair("O:"));
    List1.append(WordPair("open", "открытый, открывать	 	 "));
//    List1.append(WordPair("P:"));
    List1.append(WordPair("parallel", "параллельный, находить что-либо подобное "));
    List1.append(WordPair("past", "мимо, прошлый"));
    List1.append(WordPair("physical", "физический	"));
    List1.append(WordPair("political", "политический"));
    List1.append(WordPair("poor", "бедный, плохой, слабый"));
    List1.append(WordPair("possible", "возможный	"));
    List1.append(WordPair("present", "существующий, подарок"));
    List1.append(WordPair("private", "личный, приватный"));
    List1.append(WordPair("probable", "вероятный"));
//    List1.append(WordPair("Q:"));
    List1.append(WordPair("quick", "быстрый"));
    List1.append(WordPair("quiet", "тихий, успокаивать	 	 "));
//    List1.append(WordPair("R:"));
    List1.append(WordPair("ready", "готовый, готов"));
    List1.append(WordPair("read", "читать	"));
    List1.append(WordPair("regular", "регулярный"));
    List1.append(WordPair("responsible", "ответственный	"));
    List1.append(WordPair("right", "верный, право"));
    List1.append(WordPair("round", "вокруг, круглый, раунд"));
//    List1.append(WordPair("S:"));
    List1.append(WordPair("same", "то же самое"));
    List1.append(WordPair("second", "секунда, второй"));
    List1.append(WordPair("separate", "отдельный, отделять"));
    List1.append(WordPair("serious", "серьёзный	"));
    List1.append(WordPair("sharp", "острый"));
    List1.append(WordPair("smooth", "гладкий, мягкий, приглаживать"));
    List1.append(WordPair("sticky", "липкий"));
    List1.append(WordPair("stiff", "жесткий	"));
    List1.append(WordPair("straight", "прямой"));
    List1.append(WordPair("strong", "сильный"));
    List1.append(WordPair("sudden", "внезапный"));
    List1.append(WordPair("sweet", "сладкий"));
//    List1.append(WordPair("T:"));
    List1.append(WordPair("tall", "высокий"));
    List1.append(WordPair("thick", "толстый, густой	"));
    List1.append(WordPair("tight", "трудный"));
    List1.append(WordPair("tired", "усталый	"));
    List1.append(WordPair("true", "правда, правдивый"));
//    List1.append(WordPair("V:"));
    List1.append(WordPair("violent", "сильный, жестокий	 	 "));
//    List1.append(WordPair("W:"));
    List1.append(WordPair("waiting", "ожидание"));
    List1.append(WordPair("warm", "теплый, нагревать	"));
    List1.append(WordPair("wet", "влажный"));
    List1.append(WordPair("wide", "широкий	"));
    List1.append(WordPair("wise", "мудрый"));
//    List1.append(WordPair("Y:"));
    List1.append(WordPair("yellow", "жёлтый"));
    List1.append(WordPair("young", "молодой"));
//    List1.append(WordPair("A:"));
    List1.append(WordPair("awake", "активный, пробуждать, просыпаться	 	 "));
//    List1.append(WordPair("B:"));
    List1.append(WordPair("bad", "плохой"));
    List1.append(WordPair("bent", "склонность, сгибать	"));
    List1.append(WordPair("bitter", "горький, ожесточенный"));
    List1.append(WordPair("blue", "синий"));
//    List1.append(WordPair("C:"));
    List1.append(WordPair("certain", "уверенный, определенный"));
    List1.append(WordPair("cold", "холодный	"));
    List1.append(WordPair("complete", "полный, заканчивать"));
    List1.append(WordPair("cruel", "жестокий	 "));
//    List1.append(WordPair("D:"));
    List1.append(WordPair("dark", "темнота, темный"));
    List1.append(WordPair("dead", "мёртвый"));
    List1.append(WordPair("dear", "дорогой	"));
    List1.append(WordPair("delicate", "тонкий, деликатный"));
    List1.append(WordPair("different", "различный, другой"));
    List1.append(WordPair("dirty", "грязный	"));
    List1.append(WordPair("dry", "сухой, сушить"));
//    List1.append(WordPair("F:"));
    List1.append(WordPair("false", "фальшивый"));
    List1.append(WordPair("feeble", "слабый	"));
    List1.append(WordPair("female", "женский"));
    List1.append(WordPair("foolish", "глупый	"));
    List1.append(WordPair("future", "будущий, будущее"));
//    List1.append(WordPair("G:"));
    List1.append(WordPair("green", "зелёный	 	 "));
//    List1.append(WordPair("I:"));
    List1.append(WordPair("ill", "плохо, болеть	 	 "));
//    List1.append(WordPair("L:"));
    List1.append(WordPair("last", "последний, длиться"));
    List1.append(WordPair("late", "опаздывать	"));
    List1.append(WordPair("left", "лево, левый"));
    List1.append(WordPair("loose", "свободный, освобождать	"));
    List1.append(WordPair("loud", "громкий"));
    List1.append(WordPair("low", "низкий"));
//    List1.append(WordPair("M:"));
    List1.append(WordPair("mixed", "перемешанный	 	 "));
//    List1.append(WordPair("N:"));
    List1.append(WordPair("narrow", "узкий, сужаться	 	 "));
//    List1.append(WordPair("O:"));
    List1.append(WordPair("old", "старый"));
    List1.append(WordPair("opposite", "напротив, противоположный	 "));
//    List1.append(WordPair("P:"));
    List1.append(WordPair("public", "публичный	 	 "));
//    List1.append(WordPair("R:"));
    List1.append(WordPair("rough", "грубый	 	 "));
//    List1.append(WordPair("S:"));
    List1.append(WordPair("sad", "расстроенный"));
    List1.append(WordPair("safe", "безопасный"));
    List1.append(WordPair("secret", "секретный"));
    List1.append(WordPair("short", "короткий	"));
    List1.append(WordPair("simple", "простой"));
    List1.append(WordPair("slow", "медленный"));
    List1.append(WordPair("small", "маленький"));
    List1.append(WordPair("soft", "мягкий	"));
    List1.append(WordPair("solid", "твёрдый, солидный"));
    List1.append(WordPair("special", "специальный"));
    List1.append(WordPair("strange", "странный"));
//    List1.append(WordPair("T:"));
    List1.append(WordPair("thin", "худой, тонкий, жидкий	 	 "));
//    List1.append(WordPair("W:"));
    List1.append(WordPair("white", "белый "));
    List1.append(WordPair("wrong", "неправильный, несправедливость"));








    wList.append(WordMap("apricot", "apricots", "абрикоса", "абрикосы"));
    wList.append(WordMap("book", "books", "книга", "книги"));
    wList.append(WordMap("roof", "roofs", "крыша", "крыши"));
    wList.append(WordMap("plum", "plums", "слива", "сливы"));
    wList.append(WordMap("melon", "melons", "дыня", "дыни"));
    wList.append(WordMap("banana", "bananas", "банан", "бананы"));
    wList.append(WordMap("name", "names", "имя", "имена"));
    wList.append(WordMap("surname", "surnames", "фамилия", "фамилии"));
    wList.append(WordMap("day", "days", "день", "дни"));
    wList.append(WordMap("key", "keys", "ключ", "ключи"));
    wList.append(WordMap("life", "lives", "жизнь", "жизни"));
    wList.append(WordMap("knife", "knives", "нож", "ножи"));
    wList.append(WordMap("shelf", "shelves", "полка", "полки"));
    wList.append(WordMap("chief", "chiefs", "начальник", "начальники"));
    wList.append(WordMap("page", "pages", "страница", "страницы"));
    wList.append(WordMap("bridge", "bridges", "мост", "мосты"));
    wList.append(WordMap("orange", "oranges", "апельсин", "апельсины"));
    wList.append(WordMap("house", "houses", "дом", "дома"));
    wList.append(WordMap("lace", "laces", "кружево", "кружева"));
    wList.append(WordMap("cherry", "cherries", "вишня", "вишни"));
    wList.append(WordMap("country", "countries", "страна", "страны"));
    wList.append(WordMap("boy", "boys", "мальчик", "мальчики"));
    wList.append(WordMap("potato", "potatoes", "картофель", "картофель"));
    wList.append(WordMap("tomato", "tomatoes", "помидор", "помидоры"));
    wList.append(WordMap("photo", "photos", "фотография", "фотографии"));
    wList.append(WordMap("video", "videos", "видеомагнитофон", "видеомагнитофоны"));
    wList.append(WordMap("bus", "buses", "автобус", "автобусы"));
    wList.append(WordMap("dress", "dresses", "платье", "платья"));
    wList.append(WordMap("box", "boxes", "ящик, коробка", "ящики, коробки"));
    wList.append(WordMap("watch", "watches", "часы", "часы"));
    wList.append(WordMap("bush", "bushes", "куст", "кусты"));
    wList.append(WordMap("man", "men", "мужчина, человек", "мужчины, люди"));
    wList.append(WordMap("woman", "women", "женщина", "женщины"));
    wList.append(WordMap("foot", "feet", "нога", "ноги"));
    wList.append(WordMap("tooth", "teeth", "зуб", "зубы"));
    wList.append(WordMap("goose", "geese", "гусь", "гуси"));
    wList.append(WordMap("mouse", "mice", "мышь", "мыши"));
    wList.append(WordMap("child", "children", "ребёнок", "дети"));
    wList.append(WordMap("agendum", "agenda", "повестка дня", "повестка дня"));
    wList.append(WordMap("data", "data", "данные", "данные"));
    wList.append(WordMap("erratum", "errata", "опечатка", "опечатки"));
    wList.append(WordMap("curriculum", "curricula", "учебные планы", "учебные планы"));
    wList.append(WordMap("phenomenon", "phenomena", "явление", "явления"));
    wList.append(WordMap("analysis", "analyses", "анализ", "анализы"));
    wList.append(WordMap("axis", "axes", "ось", "оси"));
    wList.append(WordMap("basis", "bases", "основание", "основания"));
    wList.append(WordMap("thesis", "theses", "диссертация", "диссертации"));
    wList.append(WordMap("formula", "formulas", "формула", "формулы"));
    wList.append(WordMap("nucleus", "nuclei", "ядро", "ядра"));
    wList.append(WordMap("radius", "radii", "радиус", "радиусы"));
    wList.append(WordMap("appendix", "appendices", "приложение", "приложения"));
    wList.append(WordMap("index", "indices", "индекс, указатель, показатель (в мат.)", "индексы, указатели, показатели (в мат.)"));
    wList.append(WordMap("deer", "deer", "олень", "олени"));
    wList.append(WordMap("sheep", "sheep", "овца, баран", "овцы, бараны"));
    wList.append(WordMap("aircraft", "aircraft", "самолет, авиация", "самолеты, авиация"));
    wList.append(WordMap("fish", "apricots", "рыба (собир.), но тж.", "рыбы (собир.), но тж."));
    wList.append(WordMap("fishes", "apricots", "разные виды рыб", "разные виды рыб"));
    wList.append(WordMap("girl-friend", "girl-friends", "подруга", "подруги"));
    wList.append(WordMap("grown-up", "grown-ups", "взрослый", "взрослые"));
    wList.append(WordMap("forget-me-not", "forget-me-nots", "незабудка", "незабудки"));
    wList.append(WordMap("men driver", "men drivers", "водитель-мужчина", "водители мужчины"));
    wList.append(WordMap("women teacher", "women teachers", "учительница", "женщины учителя"));
    wList.append(WordMap("brother-in-law", "brothers-in-law", "зять (шурин)", "зятья (шурины)"));
    wList.append(WordMap("looker-on", "lookers-on", "зритель", "зрители"));
    expression = new ExpressionPluar;
}

void Nouns::begin()
{
    SECTION quest = SECTION(rand()%COUNT_SECTIONS);
    int index = 0;
    QString str;

    switch (quest) {
    case SECTION_PLURAL:
        index = rand()%wList.size();
        qDebug() << wList[index].word3;
        expression->setLine(wList[index].word1);
        break;
    }

}

