#include "nouns.h"

#define COUNT_SECTIONS  2

Nouns::Nouns() : BaseAction()
{




//    QList<WordPair> list1;
    list1.push_back(WordPair("angle", "fsdfa"));
    list1.push_back(WordPair("angle", "угол, поворачивать"));
    list1.push_back(WordPair("ant", "муравей"));
    list1.push_back(WordPair("apple", "яблоко"));
    list1.push_back(WordPair("arch", "арка, дуга, выгибать"));
    list1.push_back(WordPair("arm", "рука, вооружать"));
    list1.push_back(WordPair("army", "армия"));
    list1.push_back(WordPair("bag", "сумка)"));
    list1.push_back(WordPair("ball", "мяч"));
    list1.push_back(WordPair("bank", "банк"));
    list1.push_back(WordPair("basin", "бассейн"));
    list1.push_back(WordPair("basket", "корзина"));
    list1.push_back(WordPair("bath", "ванна, купаться"));
    list1.push_back(WordPair("bed", "кровать"));
    list1.push_back(WordPair("bee", "пчела"));
    list1.push_back(WordPair("bell", "колокольчик"));
    list1.push_back(WordPair("berry", "ягода"));
    list1.push_back(WordPair("bird", "птица"));
    list1.push_back(WordPair("blade", "лезвие"));
    list1.push_back(WordPair("board", "доска"));
    list1.push_back(WordPair("boat", "лодка, судно"));
    list1.push_back(WordPair("bone", "кость"));
    list1.push_back(WordPair("book", "книга"));
    list1.push_back(WordPair("boot", "ботинок, загружать"));
    list1.push_back(WordPair("bottle", "бутылка"));
    list1.push_back(WordPair("box", "коробка"));
    list1.push_back(WordPair("boy", "мальчик"));
    list1.push_back(WordPair("brain", "мозг"));
    list1.push_back(WordPair("brake", "тормоз, тормозить"));
    list1.push_back(WordPair("branch", "ветвь, отделение"));
    list1.push_back(WordPair("brick", "кирпич"));
    list1.push_back(WordPair("bridge", "мост"));
    list1.push_back(WordPair("brush", "щётка, кисть"));
    list1.push_back(WordPair("bucket", "ведро, черпать"));
    list1.push_back(WordPair("bulb", "луковица, выпирать"));
    list1.push_back(WordPair("button", "кнопка, застёгивать"));
    list1.push_back(WordPair("baby", "ребёнок, младенец"));
    list1.push_back(WordPair("cake", "пирог"));
    list1.push_back(WordPair("camera", "камера"));
    list1.push_back(WordPair("card", "карта, чесать"));
    list1.push_back(WordPair("cart", "везти"));
    list1.push_back(WordPair("carriage", "вагон"));
    list1.push_back(WordPair("cat", "кот"));
    list1.push_back(WordPair("chain", "цепь, сеть"));
    list1.push_back(WordPair("cheese", "сыр	"));
    list1.push_back(WordPair("chest", "грудь, сундук"));
    list1.push_back(WordPair("chin", "подбородок"));
    list1.push_back(WordPair("church", "церковь"));
    list1.push_back(WordPair("circle", "круг"));
    list1.push_back(WordPair("clock", "часы"));
    list1.push_back(WordPair("cloud", "облако"));
    list1.push_back(WordPair("coat", "пальто, покрывать"));
    list1.push_back(WordPair("collar", "воротник, хватать"));
    list1.push_back(WordPair("comb", "расчёсывать"));
    list1.push_back(WordPair("cord", "шнур, связывать"));
    list1.push_back(WordPair("cow", "корова"));
    list1.push_back(WordPair("cup", "чашка"));
    list1.push_back(WordPair("curtain", "занавес, штора, занавешивать"));
    list1.push_back(WordPair("cushion", "подушка, смягчать"));
    list1.push_back(WordPair("dog", "собака"));
    list1.push_back(WordPair("door", "дверь	"));
    list1.push_back(WordPair("drain", "утечка, истощать"));
    list1.push_back(WordPair("drawer", "ящик"));
    list1.push_back(WordPair("dress", "платье, одевать"));
    list1.push_back(WordPair("drop", "капля, опускать"));
    list1.push_back(WordPair("ear", "ухо"));
    list1.push_back(WordPair("egg", "яйцо"));
    list1.push_back(WordPair("engine", "двигатель"));
    list1.push_back(WordPair("eye", "глаз"));
    list1.push_back(WordPair("face", "лицо"));
    list1.push_back(WordPair("farm", "ферма"));
    list1.push_back(WordPair("feather", "перо, украшать"));
    list1.push_back(WordPair("finger", "палец"));
    list1.push_back(WordPair("fish", "рыба"));
    list1.push_back(WordPair("flag", "флаг, сигнализировать"));
    list1.push_back(WordPair("floor", "пол, этаж, дно"));
    list1.push_back(WordPair("fly", "муха, лететь"));
    list1.push_back(WordPair("foot", "нога"));
    list1.push_back(WordPair("fork", "вилка"));
    list1.push_back(WordPair("fowl", "домашняя птица"));
    list1.push_back(WordPair("frame", "структура, рамка, создавать"));
    list1.push_back(WordPair("garden", "сад"));
    list1.push_back(WordPair("girl", "девочка"));
    list1.push_back(WordPair("glove", "перчатка	"));
    list1.push_back(WordPair("goat", "коза"));
    list1.push_back(WordPair("gun", "оружие"));
    list1.push_back(WordPair("hair", "волосы"));
    list1.push_back(WordPair("hammer", "молоток"));
    list1.push_back(WordPair("hand", "рука"));
    list1.push_back(WordPair("hat", "шляпа"));
    list1.push_back(WordPair("head", "голова"));
    list1.push_back(WordPair("heart", "сердце"));
    list1.push_back(WordPair("hook", "крюк, вербовать"));
    list1.push_back(WordPair("horn", "рожок	"));
    list1.push_back(WordPair("horse", "лошадь"));
    list1.push_back(WordPair("hospital", "больница"));
    list1.push_back(WordPair("house", "дом"));

    list1.push_back(WordPair("island", "остров"));
    list1.push_back(WordPair("jewel", "драгоценный камень"));
    list1.push_back(WordPair("kettle", "чайник"));
    list1.push_back(WordPair("key", "ключ"));
    list1.push_back(WordPair("knee", "колено"));
    list1.push_back(WordPair("knife", "нож"));
    list1.push_back(WordPair("knot", "узел"));
    list1.push_back(WordPair("leaf", "лист, покрывать листвой"));
    list1.push_back(WordPair("leg", "нога"));
    list1.push_back(WordPair("library", "библиотека"));
    list1.push_back(WordPair("line", "линия, очередь, выравнивать"));
    list1.push_back(WordPair("lip", "губа"));
    list1.push_back(WordPair("lock", "замок"));
    list1.push_back(WordPair("map", "карта"));
    list1.push_back(WordPair("match", "спичка, сделки, соответствовать"));
    list1.push_back(WordPair("monkey", "обезьяна"));
    list1.push_back(WordPair("moon", "луна"));
    list1.push_back(WordPair("mouth", "рот, жевать"));
    list1.push_back(WordPair("muscle", "мускул"));
    list1.push_back(WordPair("nail", "ноготь"));
    list1.push_back(WordPair("neck", "шея, обниматься"));
    list1.push_back(WordPair("needle", "игла"));
    list1.push_back(WordPair("nerve", "нерв"));
    list1.push_back(WordPair("net", "чистый, сеть"));
    list1.push_back(WordPair("nose", "нос"));
    list1.push_back(WordPair("nut", "орех"));
    list1.push_back(WordPair("office", "офис"));
    list1.push_back(WordPair("orange", "апельсин, оранжевый"));
    list1.push_back(WordPair("oven", "духовка, печь"));
    list1.push_back(WordPair("parcel", "пакет, распределять"));
    list1.push_back(WordPair("pen", "ручка"));
    list1.push_back(WordPair("pencil", "карандаш"));
    list1.push_back(WordPair("picture", "картина"));
    list1.push_back(WordPair("pig", "свинья"));
    list1.push_back(WordPair("pin", "булавка, прикреплять"));
    list1.push_back(WordPair("pipe", "труба"));
    list1.push_back(WordPair("plane", "самолёт"));
    list1.push_back(WordPair("plate", "пластина"));
    list1.push_back(WordPair("plow", "плуг, пахать"));
    list1.push_back(WordPair("pocket", "карман, присваивать"));
    list1.push_back(WordPair("pot", "горшок"));
    list1.push_back(WordPair("potato", "картофель"));
    list1.push_back(WordPair("prison", "тюрьма"));
    list1.push_back(WordPair("pump", "насос, качать"));
    list1.push_back(WordPair("rail", "рельс, перевозить поездом"));
    list1.push_back(WordPair("rat", "крыса"));
    list1.push_back(WordPair("receipt", "квитанция"));
    list1.push_back(WordPair("ring", "кольцо, звонить"));
    list1.push_back(WordPair("rod", "прут"));
    list1.push_back(WordPair("roof", "крыша"));
    list1.push_back(WordPair("root", "корень"));
    list1.push_back(WordPair("sail", "парус"));
    list1.push_back(WordPair("school", "школа"));
    list1.push_back(WordPair("scissors", "ножницы"));
    list1.push_back(WordPair("screw", "винт"));
    list1.push_back(WordPair("seed", "семя"));
    list1.push_back(WordPair("sheep", "овцы"));
    list1.push_back(WordPair("shelf", "полка"));
    list1.push_back(WordPair("ship", "корабль"));
    list1.push_back(WordPair("shirt", "рубашка"));
    list1.push_back(WordPair("shoe", "ботинок"));
    list1.push_back(WordPair("skin", "кожа, очищать"));
    list1.push_back(WordPair("skirt", "юбка"));
    list1.push_back(WordPair("snake", "змея"));
    list1.push_back(WordPair("sock", "носок"));
    list1.push_back(WordPair("spade", "лопата"));
    list1.push_back(WordPair("sponge", "губка"));
    list1.push_back(WordPair("spoon", "ложка"));
    list1.push_back(WordPair("spring", "весна"));
    list1.push_back(WordPair("square", "квадрат"));
    list1.push_back(WordPair("stamp", "печать, марка, отпечатывать"));
    list1.push_back(WordPair("star", "звезда"));
    list1.push_back(WordPair("station", "станция"));
    list1.push_back(WordPair("stem", "стебель, происходить"));
    list1.push_back(WordPair("stick", "палка, прикреплять"));
    list1.push_back(WordPair("stocking", "снабжать"));
    list1.push_back(WordPair("stomach", "живот, смелость, переваривать"));
    list1.push_back(WordPair("store", "магазин, запас"));
    list1.push_back(WordPair("street", "улица"));
    list1.push_back(WordPair("sun", "солнце"));
    list1.push_back(WordPair("table", "стол"));
    list1.push_back(WordPair("tail", "хвост, выслеживать"));
    list1.push_back(WordPair("thread", "нить, пронизывать"));
    list1.push_back(WordPair("throat", "горло"));
    list1.push_back(WordPair("thumb", "листать, большой палец"));
    list1.push_back(WordPair("ticket", "билет"));
    list1.push_back(WordPair("toe", "палец ноги"));
    list1.push_back(WordPair("tongue", "язык"));
    list1.push_back(WordPair("tooth", "зуб"));
    list1.push_back(WordPair("town", "город	"));
    list1.push_back(WordPair("train", "поезд"));
    list1.push_back(WordPair("tray", "поднос"));
    list1.push_back(WordPair("tree", "дерево"));
    list1.push_back(WordPair("trousers", "брюки"));
    list1.push_back(WordPair("umbrella", "зонт"));
    list1.push_back(WordPair("wall", "стена"));
    list1.push_back(WordPair("watch", "часы"));
    list1.push_back(WordPair("wheel", "колесо, вертеть"));
    list1.push_back(WordPair("whip", "кнут, хлестать"));
    list1.push_back(WordPair("whistle", "свист, свистеть"));
    list1.push_back(WordPair("window", "окно"));
    list1.push_back(WordPair("wing", "крыло"));
    list1.push_back(WordPair("wire", "провод"));
    list1.push_back(WordPair("worm", "червь"));
    list1.push_back(WordPair("account", "счет, считать"));
    list1.push_back(WordPair("act", "действия"));
    list1.push_back(WordPair("addition", "дополнение"));
    list1.push_back(WordPair("adjust", "регулировать, приспосабливать"));
    list1.push_back(WordPair("advertisement", "реклама"));
    list1.push_back(WordPair("agreement", "соглашение"));
    list1.push_back(WordPair("air", "воздух, проветривать"));
    list1.push_back(WordPair("amount", "количество, означать, составлять"));
    list1.push_back(WordPair("amusement", "развлечение"));
    list1.push_back(WordPair("animal", "животное"));
    list1.push_back(WordPair("answer", "ответ, отвечать"));
    list1.push_back(WordPair("apparatus", "аппарат"));
    list1.push_back(WordPair("approval", "одобрение"));
    list1.push_back(WordPair("argument", "спор, аргумент"));
    list1.push_back(WordPair("art", "искусство, художественный"));
    list1.push_back(WordPair("attack", "нападение, нападать"));
    list1.push_back(WordPair("attempt", "попытка, пытаться"));
    list1.push_back(WordPair("attention", "внимание"));
    list1.push_back(WordPair("attraction", "достопримечательности"));
    list1.push_back(WordPair("authority", "власть, полномочие"));
    list1.push_back(WordPair("back", "назад, спина, отступать"));
    list1.push_back(WordPair("balance", "баланс, уравновешивать"));
    list1.push_back(WordPair("base", "основной"));
    list1.push_back(WordPair("behavior", "поведение"));
    list1.push_back(WordPair("belief", "вера"));
    list1.push_back(WordPair("birth", "рождение"));
    list1.push_back(WordPair("bit", "частица, бит"));
    list1.push_back(WordPair("bite", "укус, кусать"));
    list1.push_back(WordPair("blood", "кровь"));
    list1.push_back(WordPair("blow", "удар, дуть"));
    list1.push_back(WordPair("body", "тело"));
    list1.push_back(WordPair("brass", "медь, руководство"));
    list1.push_back(WordPair("bread", "хлеб"));
    list1.push_back(WordPair("breath", "дыхание"));
    list1.push_back(WordPair("brother", "брат"));
    list1.push_back(WordPair("building", "здание, строение"));
    list1.push_back(WordPair("burn", "ожог, гореть"));
    list1.push_back(WordPair("burst", "взрыв, взрывать"));
    list1.push_back(WordPair("business", "бизнес, деловой"));
    list1.push_back(WordPair("butter", "масло"));
    list1.push_back(WordPair("canvas", "холст"));
    list1.push_back(WordPair("care", "забота, лечение"));
    list1.push_back(WordPair("cause", "причина, вызывать"));
    list1.push_back(WordPair("chalk", "мел, рисовать мелом"));
    list1.push_back(WordPair("chance", "шанс, случайный, рисковать"));
    list1.push_back(WordPair("change", "изменение, замена"));
    list1.push_back(WordPair("cloth", "ткань, одежда"));
    list1.push_back(WordPair("coal", "уголь"));
    list1.push_back(WordPair("color", "цвет"));
    list1.push_back(WordPair("comfort", "комфорт"));
    list1.push_back(WordPair("committee", "комитет"));
    list1.push_back(WordPair("company", "компания"));
    list1.push_back(WordPair("comparison", "сравнение"));
    list1.push_back(WordPair("competition", "соревнование"));
    list1.push_back(WordPair("condition", "условие, обуславливать"));
    list1.push_back(WordPair("connection", "связь"));
    list1.push_back(WordPair("control", "контроль"));
    list1.push_back(WordPair("cook", "готовить"));
    list1.push_back(WordPair("copper", "медь"));
    list1.push_back(WordPair("copy", "копия"));
    list1.push_back(WordPair("cork", "пробка"));
    list1.push_back(WordPair("cotton", "хлопок"));
    list1.push_back(WordPair("cough", "кашель"));
    list1.push_back(WordPair("country", "страна"));
    list1.push_back(WordPair("cover", "покрытие, покрывать, обложка"));
    list1.push_back(WordPair("crack", "первоклассный, взламывать"));
    list1.push_back(WordPair("credit", "кредит, верить"));
    list1.push_back(WordPair("crime", "преступление"));
    list1.push_back(WordPair("crush", "давка, сокрушать"));
    list1.push_back(WordPair("cry", "плакать"));
    list1.push_back(WordPair("current", "текущий, поток"));
    list1.push_back(WordPair("curve", "кривая, избегать"));
    list1.push_back(WordPair("damage", "повреждение, повреждать"));
    list1.push_back(WordPair("danger", "опасность"));
    list1.push_back(WordPair("daughter", "дочь"));
    list1.push_back(WordPair("day", "день"));
    list1.push_back(WordPair("death", "смерть"));
    list1.push_back(WordPair("debt", "долг"));
    list1.push_back(WordPair("decision", "решение"));
    list1.push_back(WordPair("degree", "уровень, градус, степень"));
    list1.push_back(WordPair("design", "намереваться"));
    list1.push_back(WordPair("desire", "желание, желать	"));
    list1.push_back(WordPair("destruction", "разрушение"));
    list1.push_back(WordPair("detail", "детализировать, детали"));
    list1.push_back(WordPair("development", "развитие"));
    list1.push_back(WordPair("digestion", "вываривание"));
    list1.push_back(WordPair("direction", "управление"));
    list1.push_back(WordPair("discovery", "открытие"));
    list1.push_back(WordPair("discussion", "обсуждение"));
    list1.push_back(WordPair("disease", "болезнь"));
    list1.push_back(WordPair("disgust", "отвращение	"));
    list1.push_back(WordPair("distance", "дистанция"));
    list1.push_back(WordPair("distribution", "распределение"));
    list1.push_back(WordPair("division", "подразделение"));
    list1.push_back(WordPair("doubt", "сомнение"));
    list1.push_back(WordPair("drink", "пить, напиток"));
    list1.push_back(WordPair("driving", "вождение"));
    list1.push_back(WordPair("dust", "чистить, пыль"));
    list1.push_back(WordPair("earth", "земля"));
    list1.push_back(WordPair("edge", "продвигаться, край"));
    list1.push_back(WordPair("education", "образование"));
    list1.push_back(WordPair("effect", "производить, эффект"));
    list1.push_back(WordPair("end", "заканчивать, конец"));
    list1.push_back(WordPair("error", "ошибка"));
    list1.push_back(WordPair("event", "случай, событие"));
    list1.push_back(WordPair("example", "пример"));
    list1.push_back(WordPair("exchange", "обмен, обменивать"));
    list1.push_back(WordPair("existence", "существование"));
    list1.push_back(WordPair("expansion", "расширение"));
    list1.push_back(WordPair("experience", "опыт, испытывать"));
    list1.push_back(WordPair("expert", "опытный, эксперт"));
    list1.push_back(WordPair("fact", "факт"));
    list1.push_back(WordPair("fall", "падение, осень"));
    list1.push_back(WordPair("family", "семья"));
    list1.push_back(WordPair("father", "папа"));
    list1.push_back(WordPair("fear", "бояться, страх"));
    list1.push_back(WordPair("feeling", "чувство"));
    list1.push_back(WordPair("fiction", "беллетристика, фикция"));
    list1.push_back(WordPair("field", "область, поле, выставлять"));
    list1.push_back(WordPair("fight", "борьба, бороться"));
    list1.push_back(WordPair("fire", "огонь"));
    list1.push_back(WordPair("flame", "пылать, пламя"));
    list1.push_back(WordPair("flight", "полет, рейс"));
    list1.push_back(WordPair("flower", "цветок"));
    list1.push_back(WordPair("fold", "сгиб, сворачивать"));
    list1.push_back(WordPair("food", "еда, продовольствие"));
    list1.push_back(WordPair("force", "сила, вынуждать, вызывать"));
    list1.push_back(WordPair("form", "форма"));
    list1.push_back(WordPair("friend", "друг"));
    list1.push_back(WordPair("front", "выходить, фронт, передний"));
    list1.push_back(WordPair("fruit", "фрукт"));
    list1.push_back(WordPair("glass", "стекло, стакан"));
    list1.push_back(WordPair("gold", "золото"));
    list1.push_back(WordPair("government", "государство"));
    list1.push_back(WordPair("grain", "зерно"));
    list1.push_back(WordPair("grass", "трава"));
    list1.push_back(WordPair("grip", "власть, захват, захватывать"));
    list1.push_back(WordPair("group", "группа"));
    list1.push_back(WordPair("growth", "рост"));
    list1.push_back(WordPair("guide", "гид, справочник, путеводитель"));
    list1.push_back(WordPair("harbor", "приютить, питать, вставать на якорь, гавань"));
    list1.push_back(WordPair("harmony", "гармония"));
    list1.push_back(WordPair("hate", "ненавидеть, очень не хотеть, ненависть"));
    list1.push_back(WordPair("hearing", "слушание, слух"));
    list1.push_back(WordPair("heat", "нагревать, высокая температура"));
    list1.push_back(WordPair("help", "помощь, помогать"));
    list1.push_back(WordPair("history", "история"));
    list1.push_back(WordPair("hole", "продырявливать, отверстие"));
    list1.push_back(WordPair("hope", "надежда, надеяться"));
    list1.push_back(WordPair("hour", "час"));
    list1.push_back(WordPair("humor", "юмор"));
    list1.push_back(WordPair("ice", "лёд"));
    list1.push_back(WordPair("idea", "идея"));
    list1.push_back(WordPair("impulse", "импульс"));
    list1.push_back(WordPair("increase", "увеличивать, увеличение"));
    list1.push_back(WordPair("industry", "индустрия"));
    list1.push_back(WordPair("ink", "чернила"));
    list1.push_back(WordPair("insect", "насекомое"));
    list1.push_back(WordPair("instrument", "инструмент"));
    list1.push_back(WordPair("insurance", "страховка"));
    list1.push_back(WordPair("interest", "интерес, процент, доля"));
    list1.push_back(WordPair("invention", "изобретение"));
    list1.push_back(WordPair("iron", "утюг, гладить"));
    list1.push_back(WordPair("jelly", "превращать в желе, желе"));
    list1.push_back(WordPair("join", "присоединяться, объединение, соединение"));
    list1.push_back(WordPair("journey", "путешествовать, поездка"));
    list1.push_back(WordPair("judge", "судья, судить"));
    list1.push_back(WordPair("jump", "прыгать, прыжок"));
//    List1.push_back(WordPair("K:"));
    list1.push_back(WordPair("kick", "удар, ударить"));
    list1.push_back(WordPair("kiss", "поцелуй, целовать"));
    list1.push_back(WordPair("knowledge", "знание"));
//    List1.push_back(WordPair("L:"));
    list1.push_back(WordPair("land", "земля"));
    list1.push_back(WordPair("language", "язык"));
    list1.push_back(WordPair("laugh", "смеяться, смех"));
    list1.push_back(WordPair("law", "законный, закон"));
    list1.push_back(WordPair("lead", "принуждать, побеждать, вести, лидерство"));
    list1.push_back(WordPair("learning", "изучение, обучение"));
    list1.push_back(WordPair("leather", "кожа"));
    list1.push_back(WordPair("letter", "письмо"));
    list1.push_back(WordPair("level", "уровень, выравнивать, направлять"));
    list1.push_back(WordPair("lift", "поднимать, лифт"));
    list1.push_back(WordPair("light", "освещать, легкий, свет"));
    list1.push_back(WordPair("limit", "ограничивать"));
    list1.push_back(WordPair("linen", "льняной, полотно"));
    list1.push_back(WordPair("liquid", "жидкий, жидкость"));
    list1.push_back(WordPair("list", "список, перечислять"));
    list1.push_back(WordPair("loss", "потеря"));
    list1.push_back(WordPair("love", "любовь"));
//    List1.push_back(WordPair("M:"));
    list1.push_back(WordPair("machine", "машина"));
    list1.push_back(WordPair("man", "человек"));
    list1.push_back(WordPair("mark", "марка"));
    list1.push_back(WordPair("market", "рынок"));
    list1.push_back(WordPair("mass", "масса"));
    list1.push_back(WordPair("meal", "еда"));
    list1.push_back(WordPair("measure", "мера, измерять"));
    list1.push_back(WordPair("meat", "мясо"));
    list1.push_back(WordPair("meeting", "встреча"));
    list1.push_back(WordPair("memory", "память"));
    list1.push_back(WordPair("metal", "металл"));
    list1.push_back(WordPair("middle", "средний, середина"));
    list1.push_back(WordPair("milk", "молоко"));
    list1.push_back(WordPair("mind", "ум, возражать"));
    list1.push_back(WordPair("mine", "мой, месторождение, мина"));
    list1.push_back(WordPair("minute", "минута"));
    list1.push_back(WordPair("mist", "туман"));
    list1.push_back(WordPair("money", "деньги"));
    list1.push_back(WordPair("month", "месяц"));
    list1.push_back(WordPair("morning", "утро"));
    list1.push_back(WordPair("mother", "мать"));
    list1.push_back(WordPair("motion", "двигаться, движение, жест"));
    list1.push_back(WordPair("mountain", "гора, горный"));
    list1.push_back(WordPair("move", "двигать, шаг, движение"));
    list1.push_back(WordPair("music", "музыка"));
//    List1.push_back(WordPair("N:"));
    list1.push_back(WordPair("name", "имя"));
    list1.push_back(WordPair("nation", "нация"));
    list1.push_back(WordPair("need", "потребность, требоваться"));
    list1.push_back(WordPair("news", "новости"));
    list1.push_back(WordPair("night", "ночь"));
    list1.push_back(WordPair("noise", "шум"));
    list1.push_back(WordPair("note", "примечание, отмечать"));
    list1.push_back(WordPair("number", "число, номер"));
//    List1.push_back(WordPair("O:"));
    list1.push_back(WordPair("observation", "наблюдение"));
    list1.push_back(WordPair("offer", "предложение, предлагать"));
    list1.push_back(WordPair("oil", "масло"));
    list1.push_back(WordPair("operation", "операция, действие"));
    list1.push_back(WordPair("opinion", "мнение"));
    list1.push_back(WordPair("order", "заказ, заказывать, приказывать"));
    list1.push_back(WordPair("organization", "организация"));
    list1.push_back(WordPair("ornament", "украшение, украшать"));
    list1.push_back(WordPair("owner", "владелец"));
//    List1.push_back(WordPair("P:"));
    list1.push_back(WordPair("page", "страница"));
    list1.push_back(WordPair("pain", "боль, причинять боль"));
    list1.push_back(WordPair("paint", "краска, рисовать, красить"));
    list1.push_back(WordPair("paper", "бумага"));
    list1.push_back(WordPair("part", "часть, отделять, разделяться"));
    list1.push_back(WordPair("paste", "приклеивать, паста"));
    list1.push_back(WordPair("payment", "оплата"));
    list1.push_back(WordPair("peace", "мир"));
    list1.push_back(WordPair("person", "персона"));
    list1.push_back(WordPair("place", "размещать, помещать, занимать место, место"));
    list1.push_back(WordPair("plant", "завод, растение, прививать, сеять"));
    list1.push_back(WordPair("play", "играть"));
    list1.push_back(WordPair("pleasure", "удовольствие"));
    list1.push_back(WordPair("point", "пункт, точка, указывать"));
    list1.push_back(WordPair("poison", "яд, отравлять"));
    list1.push_back(WordPair("polish", "полировать"));
    list1.push_back(WordPair("porter", "швейцар,носильщик"));
    list1.push_back(WordPair("position", "помещать, позиция"));
    list1.push_back(WordPair("powder", "порошок"));
    list1.push_back(WordPair("power", "сила, власть"));
    list1.push_back(WordPair("price", "цена"));
    list1.push_back(WordPair("print", "печатать"));
    list1.push_back(WordPair("process", "обрабатывать, процесс"));
    list1.push_back(WordPair("produce", "продукт, производить"));
    list1.push_back(WordPair("profit", "прибыль, получать прибыль"));
    list1.push_back(WordPair("property", "свойства"));
    list1.push_back(WordPair("prose", "проза"));
    list1.push_back(WordPair("protest", "возражать, протест"));
    list1.push_back(WordPair("pull", "напряжение, тянуть"));
    list1.push_back(WordPair("punishment", "наказание"));
    list1.push_back(WordPair("purpose", "намереваться, цель"));
    list1.push_back(WordPair("push", "толчок, подталкивать"));
//    List1.push_back(WordPair("Q:"));
    list1.push_back(WordPair("quality", "качество, качественный"));
    list1.push_back(WordPair("question", "вопрос"));
//    List1.push_back(WordPair("R:"));
    list1.push_back(WordPair("rain", "дождь"));
    list1.push_back(WordPair("range", "диапазон, располагаться"));
    list1.push_back(WordPair("rate", "норма,разряд"));
    list1.push_back(WordPair("ray", "луч"));
    list1.push_back(WordPair("reaction", "реакция"));
    list1.push_back(WordPair("reading", "чтение"));
    list1.push_back(WordPair("reason", "рассуждать, причина, разум"));
    list1.push_back(WordPair("record", "рекордный, отчёт, делать запись"));
    list1.push_back(WordPair("regret", "сожаление, сожалеть"));
    list1.push_back(WordPair("relation", "отношение"));
    list1.push_back(WordPair("religion", "религия"));
    list1.push_back(WordPair("representative", "представитель"));
    list1.push_back(WordPair("request", "запрос, просить"));
    list1.push_back(WordPair("respect", "уважение, уважать"));
    list1.push_back(WordPair("rest", "отдых, отдыхать, оставаться"));
    list1.push_back(WordPair("reward", "награда, вознаграждать"));
    list1.push_back(WordPair("rhythm", "ритм"));
    list1.push_back(WordPair("rice", "рис"));
    list1.push_back(WordPair("river", "река"));
    list1.push_back(WordPair("road", "дорога"));
    list1.push_back(WordPair("roll", "рулон, ведомость, катиться, въезжать"));
    list1.push_back(WordPair("room", "комната"));
    list1.push_back(WordPair("rub", "протирать, тереться"));
    list1.push_back(WordPair("rule", "правило"));
    list1.push_back(WordPair("run", "бег, бегать"));
//    List1.push_back(WordPair("S:"));
    list1.push_back(WordPair("salt", "соль, солить"));
    list1.push_back(WordPair("sand", "песок"));
    list1.push_back(WordPair("scale", "измерять, масштаб"));
    list1.push_back(WordPair("science", "наука"));
    list1.push_back(WordPair("sea", "море"));
    list1.push_back(WordPair("seat", "сиденье, усаживать, место"));
    list1.push_back(WordPair("secretary", "секретарь"));
    list1.push_back(WordPair("selection", "выбор"));
    list1.push_back(WordPair("self", "сам"));
    list1.push_back(WordPair("sense", "чувство, значения, смысл, ощущать"));
    list1.push_back(WordPair("servant", "слуга"));
    list1.push_back(WordPair("sex", "секс, пол"));
    list1.push_back(WordPair("shade", "оттенок,тень, заштриховывать"));
    list1.push_back(WordPair("shake", "встряска, встряхивать, дрожать, потрясать"));
    list1.push_back(WordPair("shame", "позор, позорить"));
    list1.push_back(WordPair("shock", "шок, потрясать"));
    list1.push_back(WordPair("side", "сторона, примыкать"));
    list1.push_back(WordPair("sign", "знак, признак, подписывать"));
    list1.push_back(WordPair("silk", "шёлк"));
    list1.push_back(WordPair("silver", "серебро	"));
    list1.push_back(WordPair("sister", "сестра"));
    list1.push_back(WordPair("size", "размер"));
    list1.push_back(WordPair("sky", "небо"));
    list1.push_back(WordPair("sleep", "спать"));
    list1.push_back(WordPair("slip", "промах, бланк, подсовывать, скользить"));
    list1.push_back(WordPair("slope", "наклон, клониться"));
    list1.push_back(WordPair("smash", "удар, разбиваться"));
    list1.push_back(WordPair("smell", "запах, пахнуть"));
    list1.push_back(WordPair("smile", "улыбка, улыбаться"));
    list1.push_back(WordPair("smoke", "дым, курить"));
    list1.push_back(WordPair("sneeze", "чиханье, чихать"));
    list1.push_back(WordPair("snow", "снег"));
    list1.push_back(WordPair("soap", "мыло, мылить"));
    list1.push_back(WordPair("society", "общество"));
    list1.push_back(WordPair("son", "сын"));
    list1.push_back(WordPair("song", "песня"));
    list1.push_back(WordPair("sort", "вид, сортировать"));
    list1.push_back(WordPair("sound", "звук"));
    list1.push_back(WordPair("soup", "суп"));
    list1.push_back(WordPair("space", "пространство, космос"));
    list1.push_back(WordPair("stage", "стадия, сцена, организовывать"));
    list1.push_back(WordPair("start", "начинать"));
    list1.push_back(WordPair("statement", "утверждение"));
    list1.push_back(WordPair("steam", "пар, париться, двигаться"));
    list1.push_back(WordPair("steel", "сталь"));
    list1.push_back(WordPair("step", "шаг, шагать"));
    list1.push_back(WordPair("stitch", "стежок, сшивать"));
    list1.push_back(WordPair("stone", "камень"));
    list1.push_back(WordPair("stop", "останавливаться, остановка"));
    list1.push_back(WordPair("story", "история"));
    list1.push_back(WordPair("stretch", "отрезки, протягивать, простираться"));
    list1.push_back(WordPair("structure", "структура"));
    list1.push_back(WordPair("substance", "вещество, сущность"));
    list1.push_back(WordPair("sugar", "сахар"));
    list1.push_back(WordPair("suggestion", "предложение, предположение"));
    list1.push_back(WordPair("summer", "лето"));
    list1.push_back(WordPair("support", "поддержка, поддерживать"));
    list1.push_back(WordPair("surprise", "сюрприз"));
    list1.push_back(WordPair("swim", "плаванье, плавать"));
    list1.push_back(WordPair("system", "система"));
//    List1.push_back(WordPair("T:"));
    list1.push_back(WordPair("talk", "разговор, говорить"));
    list1.push_back(WordPair("taste", "вкус, испытывать"));
    list1.push_back(WordPair("tax", "налог, облагать налогом"));
    list1.push_back(WordPair("teaching", "обучение"));
    list1.push_back(WordPair("tendency", "тенденция"));
    list1.push_back(WordPair("test", "проверять, тест"));
    list1.push_back(WordPair("theory", "теория"));
    list1.push_back(WordPair("thing", "вещь"));
    list1.push_back(WordPair("thought", "мысль"));
    list1.push_back(WordPair("thunder", "гром, греметь"));
    list1.push_back(WordPair("time", "время"));
    list1.push_back(WordPair("tin", "олово,консервная банка"));
    list1.push_back(WordPair("top", "возглавлять, вершина, главный"));
    list1.push_back(WordPair("touch", "прикосновение, касаться"));
    list1.push_back(WordPair("trade", "торговля, обменивать"));
    list1.push_back(WordPair("transport ", "транспорт, транспортировать"));
    list1.push_back(WordPair("trick", "уловка, обманывать"));
    list1.push_back(WordPair("trouble", "проблема, беспокоить"));
    list1.push_back(WordPair("turn", "поворот, поворачивать"));
    list1.push_back(WordPair("twist", "завихрение, крутить"));
//    List1.push_back(WordPair("U:"));
    list1.push_back(WordPair("unit", "единица"));
    list1.push_back(WordPair("use", "использование, использовать"));
//    List1.push_back(WordPair("V:"));
    list1.push_back(WordPair("value", "ценность, оценивать"));
    list1.push_back(WordPair("verse", "стих"));
    list1.push_back(WordPair("vessel", "судно, сосуд"));
    list1.push_back(WordPair("view", "вид, взгляд, рассматривать"));
    list1.push_back(WordPair("voice", "голос, высказывать"));
//    List1.push_back(WordPair("W:"));
    list1.push_back(WordPair("war", "война"));
    list1.push_back(WordPair("wash", "мытьё, стирать, чистить"));
    list1.push_back(WordPair("waste", "ненужный, отходы, трата"));
    list1.push_back(WordPair("water", "вода"));
    list1.push_back(WordPair("wave", "волна"));
    list1.push_back(WordPair("wax", "воск, натирать воском"));
    list1.push_back(WordPair("weather", "погода"));
    list1.push_back(WordPair("week", "неделя"));
    list1.push_back(WordPair("weight", "вес, нагружать"));
    list1.push_back(WordPair("wind", "ветер"));
    list1.push_back(WordPair("wine", "вино"));
    list1.push_back(WordPair("winter", "зима, зимовать"));
    list1.push_back(WordPair("woman", "женщина"));
    list1.push_back(WordPair("wood", "лес"));
    list1.push_back(WordPair("wool", "шерсть"));
    list1.push_back(WordPair("word", "слово"));
    list1.push_back(WordPair("work", "работа, работать"));
    list1.push_back(WordPair("wound", "проветривать, рана, ранить"));
    list1.push_back(WordPair("writing", "письмо"));
//    List1.push_back(WordPair("Y:"));
    list1.push_back(WordPair("year", "год"));
    list1.push_back(WordPair("come", "приходить, приезжать"));
    list1.push_back(WordPair("get", "получать, заставлять"));
    list1.push_back(WordPair("give", "давать"));
    list1.push_back(WordPair("go", "ходить, идти"));
    list1.push_back(WordPair("keep", "продолжать, держать, оставлять, не допускать"));
    list1.push_back(WordPair("let", "позволять"));
    list1.push_back(WordPair("make", "делать/сделать, заставлять"));
    list1.push_back(WordPair("put", "помещать"));
    list1.push_back(WordPair("seem", "казаться, представляться"));
    list1.push_back(WordPair("take", "брать/взять"));
    list1.push_back(WordPair("be", "быть"));
    list1.push_back(WordPair("do", "делать"));
    list1.push_back(WordPair("have", "иметь, съесть, знать"));
    list1.push_back(WordPair("say", "говорить"));
    list1.push_back(WordPair("see", "видеть"));
    list1.push_back(WordPair("send", "посылать"));
    list1.push_back(WordPair("may", "мочь"));
    list1.push_back(WordPair("will", "быть хотеть"));
    list1.push_back(WordPair("about", "о"));
    list1.push_back(WordPair("across", "через"));
    list1.push_back(WordPair("after", "после"));
    list1.push_back(WordPair("against", "против"));
    list1.push_back(WordPair("among", "среди"));
    list1.push_back(WordPair("at", "в"));
    list1.push_back(WordPair("before", "перед"));
    list1.push_back(WordPair("between", "между"));
    list1.push_back(WordPair("by", "к, в соответствии с, за, на"));
    list1.push_back(WordPair("down", "вниз"));
    list1.push_back(WordPair("from", "из"));
    list1.push_back(WordPair("in", "в"));
    list1.push_back(WordPair("off", "прочь, от"));
    list1.push_back(WordPair("on", "на"));
    list1.push_back(WordPair("over", "по"));
    list1.push_back(WordPair("through", "через"));
    list1.push_back(WordPair("to", "к, до, в"));
    list1.push_back(WordPair("under", "под"));
    list1.push_back(WordPair("up", "вверх"));
    list1.push_back(WordPair("with", "с"));
    list1.push_back(WordPair("as", "поскольку, как"));
    list1.push_back(WordPair("for", "для"));
    list1.push_back(WordPair("of", "из, о, от"));
    list1.push_back(WordPair("till", "пока, до"));
    list1.push_back(WordPair("than", "чем"));
    list1.push_back(WordPair("a", "любой, один, каждый, некий"));
    list1.push_back(WordPair("all", "все, весь"));
    list1.push_back(WordPair("any", "любой, никто"));
    list1.push_back(WordPair("every", "каждый"));
    list1.push_back(WordPair("no", "никакой, нет"));
    list1.push_back(WordPair("other", "другой"));
    list1.push_back(WordPair("some", "некоторый, немного"));
    list1.push_back(WordPair("such", "такой, таким образом"));
    list1.push_back(WordPair("that", "что"));
    list1.push_back(WordPair("this", "это, этот"));
    list1.push_back(WordPair("i", "я"));
    list1.push_back(WordPair("he", "он"));
    list1.push_back(WordPair("you", "ты, вы"));
    list1.push_back(WordPair("who", "кто"));
    list1.push_back(WordPair("and", "и"));
    list1.push_back(WordPair("because", "потому что"));
    list1.push_back(WordPair("but", "а, но"));
    list1.push_back(WordPair("or", "или"));
    list1.push_back(WordPair("if", "если"));
    list1.push_back(WordPair("though", "хотя"));
    list1.push_back(WordPair("while", "в то время как"));
    list1.push_back(WordPair("how", "как"));
    list1.push_back(WordPair("when", "когда"));
    list1.push_back(WordPair("where", "где, куда, откуда"));
    list1.push_back(WordPair("why", "почему"));
    list1.push_back(WordPair("again", "снова"));
    list1.push_back(WordPair("ever", "когда-либо, никогда"));
    list1.push_back(WordPair("far", "самый дальний"));
    list1.push_back(WordPair("forward", "отправлять, вперед"));
    list1.push_back(WordPair("here", "здесь, сюда"));
    list1.push_back(WordPair("near", "рядом, около"));
    list1.push_back(WordPair("now", "теперь, сейчас"));
    list1.push_back(WordPair("out", "вне, снаружи"));
    list1.push_back(WordPair("still", "все еще"));
    list1.push_back(WordPair("then", "тогда"));
    list1.push_back(WordPair("there", "там, туда"));
    list1.push_back(WordPair("together", "вместе"));
    list1.push_back(WordPair("well", "хорошо, намного"));
    list1.push_back(WordPair("almost", "почти"));
    list1.push_back(WordPair("enough", "достаточно"));
    list1.push_back(WordPair("even", "еще, даже"));
    list1.push_back(WordPair("little", "маленький"));
    list1.push_back(WordPair("much", "много"));
    list1.push_back(WordPair("not", "не"));
    list1.push_back(WordPair("only", "только"));
    list1.push_back(WordPair("quite", "весьма"));
    list1.push_back(WordPair("so", "так"));
    list1.push_back(WordPair("very", "очень"));
    list1.push_back(WordPair("tomorrow", "завтра"));
    list1.push_back(WordPair("yesterday", "вчера"));
    list1.push_back(WordPair("north", "север"));
    list1.push_back(WordPair("south", "юг"));
    list1.push_back(WordPair("east", "восток"));
    list1.push_back(WordPair("west", "запад"));
    list1.push_back(WordPair("please", "пожалуйста"));
    list1.push_back(WordPair("yes", "да"));
//    List1.push_back(WordPair("A:"));
    list1.push_back(WordPair("able", "способный, быть в состоянии"));
    list1.push_back(WordPair("acid", "кислота, кислый"));
    list1.push_back(WordPair("angry", "сердитый"));
//    List1.push_back(WordPair("B:"));
    list1.push_back(WordPair("beautiful", "красивый"));
    list1.push_back(WordPair("black", "чёрный"));
    list1.push_back(WordPair("boiling", "кипение"));
    list1.push_back(WordPair("bright", "яркий, умный"));
    list1.push_back(WordPair("broken", "сломанный"));
    list1.push_back(WordPair("brown", "коричневый"));
//    List1.push_back(WordPair("C:"));
    list1.push_back(WordPair("cheap", "дешёвый"));
    list1.push_back(WordPair("chemical", "химикат"));
    list1.push_back(WordPair("chief", "главный	"));
    list1.push_back(WordPair("clean", "чистый, чистить"));
    list1.push_back(WordPair("clear", "ясный, очищать, оправдываться"));
    list1.push_back(WordPair("common", "общий"));
    list1.push_back(WordPair("complex", "комплекс"));
    list1.push_back(WordPair("conscious", "сознательный"));
    list1.push_back(WordPair("cut", "резать"));
//    List1.push_back(WordPair("D:"));
    list1.push_back(WordPair("deep", "глубокий, глубоко	"));
    list1.push_back(WordPair("dependent", "зависимый"));
//    List1.push_back(WordPair("E:"));
    list1.push_back(WordPair("early", "рано, ранний	"));
    list1.push_back(WordPair("elastic", "эластичный	"));
    list1.push_back(WordPair("equal", "равный, равняться"));
//    List1.push_back(WordPair("F:"));
    list1.push_back(WordPair("fat", "толстый, жир"));
    list1.push_back(WordPair("fertile", "плодородный"));
    list1.push_back(WordPair("first", "первый"));
    list1.push_back(WordPair("fixed", "неподвижный, неизменный"));
    list1.push_back(WordPair("flat", "плоский, квартира, плоскость"));
    list1.push_back(WordPair("free", "свобода, бесплатный"));
    list1.push_back(WordPair("frequent", "частый, часто посещать"));
    list1.push_back(WordPair("full", "полный"));
//    List1.push_back(WordPair("G:"));
    list1.push_back(WordPair("general", "общий, генерал"));
    list1.push_back(WordPair("good", "хороший"));
    list1.push_back(WordPair("great", "великий, великолепный"));
    list1.push_back(WordPair("grey|gray", "серый"));
//    List1.push_back(WordPair("H:"));
    list1.push_back(WordPair("hanging", "вывешивание, висение"));
    list1.push_back(WordPair("happy", "счастье"));
    list1.push_back(WordPair("hard", "трудный, тяжёлый, твёрдый"));
    list1.push_back(WordPair("healthy", "здоровый"));
    list1.push_back(WordPair("high", "высокий, высоко"));
    list1.push_back(WordPair("hollow", "пустота"));
//    List1.push_back(WordPair("I:"));
    list1.push_back(WordPair("important", "важный"));
//    List1.push_back(WordPair("J:"));
    list1.push_back(WordPair("jewel", "драгоценный камень"));
//    List1.push_back(WordPair("K:"));
    list1.push_back(WordPair("kind", "добрый, вид"));
//    List1.push_back(WordPair("L:"));
    list1.push_back(WordPair("like", "подобный, любить, нравиться"));
    list1.push_back(WordPair("living", "проживаниe"));
    list1.push_back(WordPair("long", "долго, длинный"));
//    List1.push_back(WordPair("M:"));
    list1.push_back(WordPair("male", "мужской, мужчина"));
    list1.push_back(WordPair("married", "женатый, замужем"));
    list1.push_back(WordPair("material", "материал"));
    list1.push_back(WordPair("medical", "медицинский"));
    list1.push_back(WordPair("military", "военный"));
//    List1.push_back(WordPair("N:"));
    list1.push_back(WordPair("natural", "натуральный"));
    list1.push_back(WordPair("necessary", "необходимый"));
    list1.push_back(WordPair("new", "новый"));
    list1.push_back(WordPair("normal", "нормальный"));
//    List1.push_back(WordPair("O:"));
    list1.push_back(WordPair("open", "открытый, открывать"));
//    List1.push_back(WordPair("P:"));
    list1.push_back(WordPair("parallel", "параллельный, находить что-либо подобное"));
    list1.push_back(WordPair("past", "мимо, прошлый"));
    list1.push_back(WordPair("physical", "физический"));
    list1.push_back(WordPair("political", "политический"));
    list1.push_back(WordPair("poor", "бедный, плохой, слабый"));
    list1.push_back(WordPair("possible", "возможный"));
    list1.push_back(WordPair("present", "существующий, подарок"));
    list1.push_back(WordPair("private", "личный, приватный"));
    list1.push_back(WordPair("probable", "вероятный"));
//    List1.push_back(WordPair("Q:"));
    list1.push_back(WordPair("quick", "быстрый"));
    list1.push_back(WordPair("quiet", "тихий, успокаивать"));
//    List1.push_back(WordPair("R:"));
    list1.push_back(WordPair("ready", "готовый, готов"));
    list1.push_back(WordPair("read", "читать"));
    list1.push_back(WordPair("regular", "регулярный"));
    list1.push_back(WordPair("responsible", "ответственный"));
    list1.push_back(WordPair("right", "верный, право"));
    list1.push_back(WordPair("round", "вокруг, круглый, раунд"));
//    List1.push_back(WordPair("S:"));
    list1.push_back(WordPair("same", "то же самое"));
    list1.push_back(WordPair("second", "секунда, второй"));
    list1.push_back(WordPair("separate", "отдельный, отделять"));
    list1.push_back(WordPair("serious", "серьёзный"));
    list1.push_back(WordPair("sharp", "острый"));
    list1.push_back(WordPair("smooth", "гладкий, мягкий, приглаживать"));
    list1.push_back(WordPair("sticky", "липкий"));
    list1.push_back(WordPair("stiff", "жесткий"));
    list1.push_back(WordPair("straight", "прямой"));
    list1.push_back(WordPair("strong", "сильный"));
    list1.push_back(WordPair("sudden", "внезапный"));
    list1.push_back(WordPair("sweet", "сладкий"));
//    List1.push_back(WordPair("T:"));
    list1.push_back(WordPair("tall", "высокий"));
    list1.push_back(WordPair("thick", "толстый, густой"));
    list1.push_back(WordPair("tight", "трудный"));
    list1.push_back(WordPair("tired", "усталый"));
    list1.push_back(WordPair("true", "правда, правдивый"));
//    List1.push_back(WordPair("V:"));
    list1.push_back(WordPair("violent", "сильный, жестокий"));
//    List1.push_back(WordPair("W:"));
    list1.push_back(WordPair("waiting", "ожидание"));
    list1.push_back(WordPair("warm", "теплый, нагревать"));
    list1.push_back(WordPair("wet", "влажный"));
    list1.push_back(WordPair("wide", "широкий"));
    list1.push_back(WordPair("wise", "мудрый"));
//    List1.push_back(WordPair("Y:"));
    list1.push_back(WordPair("yellow", "жёлтый"));
    list1.push_back(WordPair("young", "молодой"));
//    List1.push_back(WordPair("A:"));
    list1.push_back(WordPair("awake", "активный, пробуждать, просыпаться"));
//    List1.push_back(WordPair("B:"));
    list1.push_back(WordPair("bad", "плохой"));
    list1.push_back(WordPair("bent", "склонность, сгибать"));
    list1.push_back(WordPair("bitter", "горький, ожесточенный"));
    list1.push_back(WordPair("blue", "синий"));
//    List1.push_back(WordPair("C:"));
    list1.push_back(WordPair("certain", "уверенный, определенный"));
    list1.push_back(WordPair("cold", "холодный"));
    list1.push_back(WordPair("complete", "полный, заканчивать"));
    list1.push_back(WordPair("cruel", "жестокий"));
//    List1.push_back(WordPair("D:"));
    list1.push_back(WordPair("dark", "темнота, темный"));
    list1.push_back(WordPair("dead", "мёртвый"));
    list1.push_back(WordPair("dear", "дорогой"));
    list1.push_back(WordPair("delicate", "тонкий, деликатный"));
    list1.push_back(WordPair("different", "различный, другой"));
    list1.push_back(WordPair("dirty", "грязный"));
    list1.push_back(WordPair("dry", "сухой, сушить"));
//    List1.push_back(WordPair("F:"));
    list1.push_back(WordPair("false", "фальшивый"));
    list1.push_back(WordPair("feeble", "слабый"));
    list1.push_back(WordPair("female", "женский"));
    list1.push_back(WordPair("foolish", "глупый"));
    list1.push_back(WordPair("future", "будущий, будущее"));
//    List1.push_back(WordPair("G:"));
    list1.push_back(WordPair("green", "зелёный"));
//    List1.push_back(WordPair("I:"));
    list1.push_back(WordPair("ill", "плохо, болеть"));
//    List1.push_back(WordPair("L:"));
    list1.push_back(WordPair("last", "последний, длиться"));
    list1.push_back(WordPair("late", "опаздывать"));
    list1.push_back(WordPair("left", "лево, левый"));
    list1.push_back(WordPair("loose", "свободный, освобождать"));
    list1.push_back(WordPair("loud", "громкий"));
    list1.push_back(WordPair("low", "низкий"));
//    List1.push_back(WordPair("M:"));
    list1.push_back(WordPair("mixed", "перемешанный"));
//    List1.push_back(WordPair("N:"));
    list1.push_back(WordPair("narrow", "узкий, сужаться"));
//    List1.push_back(WordPair("O:"));
    list1.push_back(WordPair("old", "старый"));
    list1.push_back(WordPair("opposite", "напротив, противоположный"));
//    List1.push_back(WordPair("P:"));
    list1.push_back(WordPair("public", "публичный"));
//    List1.push_back(WordPair("R:"));
    list1.push_back(WordPair("rough", "грубый"));
//    List1.push_back(WordPair("S:"));
    list1.push_back(WordPair("sad", "расстроенный"));
    list1.push_back(WordPair("safe", "безопасный"));
    list1.push_back(WordPair("secret", "секретный"));
    list1.push_back(WordPair("short", "короткий	"));
    list1.push_back(WordPair("simple", "простой"));
    list1.push_back(WordPair("slow", "медленный"));
    list1.push_back(WordPair("small", "маленький"));
    list1.push_back(WordPair("soft", "мягкий"));
    list1.push_back(WordPair("solid", "твёрдый, солидный"));
    list1.push_back(WordPair("special", "специальный"));
    list1.push_back(WordPair("strange", "странный"));
//    List1.push_back(WordPair("T:"));
    list1.push_back(WordPair("thin", "худой, тонкий, жидкий"));
//    List1.push_back(WordPair("W:"));
    list1.push_back(WordPair("white", "белый"));
    list1.push_back(WordPair("wrong", "неправильный, несправедливость"));








    wList.append(WordMap("apricot", "apricots", "абрикоса", "абрикосы"));
    wList.append(WordMap("book", "books", "книга", "книги"));
    wList.append(WordMap("roof", "roofs", "крыша", "крыши"));
    wList.append(WordMap("plum", "plums", "слива", "сливы"));
    wList.append(WordMap("melon", "melons", "дыня", "дыни"));
    wList.append(WordMap("banana", "bananas", "банан", "бананы"));
    wList.append(WordMap("name", "names", "имя", "имена"));
    wList.append(WordMap("surname", "surnames", "фамилия", "фамилии"));
    wList.append(WordMap("day", "days", "день", "дни"));
    wList.append(WordMap("key", "keys", "ключ", "ключи"));
    wList.append(WordMap("life", "lives", "жизнь", "жизни"));
    wList.append(WordMap("knife", "knives", "нож", "ножи"));
    wList.append(WordMap("shelf", "shelves", "полка", "полки"));
    wList.append(WordMap("chief", "chiefs", "начальник", "начальники"));
    wList.append(WordMap("page", "pages", "страница", "страницы"));
    wList.append(WordMap("bridge", "bridges", "мост", "мосты"));
    wList.append(WordMap("orange", "oranges", "апельсин", "апельсины"));
    wList.append(WordMap("house", "houses", "дом", "дома"));
    wList.append(WordMap("lace", "laces", "кружево", "кружева"));
    wList.append(WordMap("cherry", "cherries", "вишня", "вишни"));
    wList.append(WordMap("country", "countries", "страна", "страны"));
    wList.append(WordMap("boy", "boys", "мальчик", "мальчики"));
    wList.append(WordMap("potato", "potatoes", "картофель", "картофель"));
    wList.append(WordMap("tomato", "tomatoes", "помидор", "помидоры"));
    wList.append(WordMap("photo", "photos", "фотография", "фотографии"));
    wList.append(WordMap("video", "videos", "видеомагнитофон", "видеомагнитофоны"));
    wList.append(WordMap("bus", "buses", "автобус", "автобусы"));
    wList.append(WordMap("dress", "dresses", "платье", "платья"));
    wList.append(WordMap("box", "boxes", "ящик, коробка", "ящики, коробки"));
    wList.append(WordMap("watch", "watches", "часы", "часы"));
    wList.append(WordMap("bush", "bushes", "куст", "кусты"));
    wList.append(WordMap("man", "men", "мужчина, человек", "мужчины, люди"));
    wList.append(WordMap("woman", "women", "женщина", "женщины"));
    wList.append(WordMap("foot", "feet", "нога", "ноги"));
    wList.append(WordMap("tooth", "teeth", "зуб", "зубы"));
    wList.append(WordMap("goose", "geese", "гусь", "гуси"));
    wList.append(WordMap("mouse", "mice", "мышь", "мыши"));
    wList.append(WordMap("child", "children", "ребёнок", "дети"));
    wList.append(WordMap("agendum", "agenda", "повестка дня", "повестка дня"));
    wList.append(WordMap("data", "data", "данные", "данные"));
    wList.append(WordMap("erratum", "errata", "опечатка", "опечатки"));
    wList.append(WordMap("curriculum", "curricula", "учебные планы", "учебные планы"));
    wList.append(WordMap("phenomenon", "phenomena", "явление", "явления"));
    wList.append(WordMap("analysis", "analyses", "анализ", "анализы"));
    wList.append(WordMap("axis", "axes", "ось", "оси"));
    wList.append(WordMap("basis", "bases", "основание", "основания"));
    wList.append(WordMap("thesis", "theses", "диссертация", "диссертации"));
    wList.append(WordMap("formula", "formulas", "формула", "формулы"));
    wList.append(WordMap("nucleus", "nuclei", "ядро", "ядра"));
    wList.append(WordMap("radius", "radii", "радиус", "радиусы"));
    wList.append(WordMap("appendix", "appendices", "приложение", "приложения"));
    wList.append(WordMap("index", "indices", "индекс, указатель, показатель (в мат.)", "индексы, указатели, показатели (в мат.)"));
    wList.append(WordMap("deer", "deer", "олень", "олени"));
    wList.append(WordMap("sheep", "sheep", "овца, баран", "овцы, бараны"));
    wList.append(WordMap("aircraft", "aircraft", "самолет, авиация", "самолеты, авиация"));
    wList.append(WordMap("fish", "fishes", "рыба (собир.), но тж.", "рыбы (собир.), но тж."));
    wList.append(WordMap("girl-friend", "girl-friends", "подруга", "подруги"));
    wList.append(WordMap("grown-up", "grown-ups", "взрослый", "взрослые"));
    wList.append(WordMap("forget-me-not", "forget-me-nots", "незабудка", "незабудки"));
    wList.append(WordMap("men driver", "men drivers", "водитель-мужчина", "водители мужчины"));
    wList.append(WordMap("women teacher", "women teachers", "учительница", "женщины учителя"));
    wList.append(WordMap("brother-in-law", "brothers-in-law", "зять (шурин)", "зятья (шурины)"));
    wList.append(WordMap("looker-on", "lookers-on", "зритель", "зрители"));
    expression = new ExpressionPluar;
}

void Nouns::begin(int number)
{
    int index1 = rand()%2;

    SECTION quest = SECTION(rand()%COUNT_SECTIONS);
    int index = 0;
    bool english = false;
    if(number != -1)
        english = number;
    else
        english = rand()%2;
    QString str;

    switch (quest) {
    case SECTION_PLURAL:


        if(index1 == 0) {
            qDebug() <<  "\nЕдинственное число существительное ";
            index = rand()%wList.size();
            if(english) {
                qDebug() << wList[index].word1;
                expression->setLine(wList[index].word3);
            } else {
                qDebug() << wList[index].word3;
                expression->setLine(wList[index].word1);
            }
        } else {
            qDebug() <<  "\nМножественное число существительных ";
            index = rand()%wList.size();
            if(english) {
                qDebug() << wList[index].word2;
                expression->setLine(wList[index].word4);
            } else {
                qDebug() << wList[index].word4;
                expression->setLine(wList[index].word2);
            }

        }
        break;
    case SECTION_WORDS:
        qDebug() <<  "\nЕдинственное число существительное ";
        index = rand()%list1.size();
        if(english) {
            qDebug() << list1[index].word1;
            expression->setLine(list1[index].word2);
        } else {
            qDebug() << list1[index].word2;
            expression->setLine(list1[index].word1);
        }
        break;
    }

}

